### ISSUE TITLE
how to use LinearTransform if we want to not just sum all slots?

### ISSUE THREAD

**Issue by extrame** [tuneinsight/lattigo#173]
LinearTransform is useful if I pass matrix (assume slot is 4)
0:1 1 1 1
1:1 1 1 1
2:1 1 1 1
3:1 1 1 1

right, It will add all slots

0:1 1 1 1

right, will get value as input 

0:1 0 0 0
1:1 0 0 0
2:1 0 0 0
3:1 0 0 0

will get all zero...why???

Add when I want to keep slot0,but sum slot[1:]:

From ckks_test.go, I know each key N in matrix pass to ckks.GenLinearTransform means the vec used for slot with offset(N)

So I try to pass
0:1 1 1 1 // add self
1:0 1 1 0 // slot1,2 add n+1, so slot1=slot1+slot2,slot2=slot2+slot3,
2:0 1 0 1 //slot 1,3 add n+2, so slot1=slot1+slot2+slot3,slot2=slot2+slot3,slot3=slot3+slot1,
3:0 0 1 1 //slot 2,3 add n+3, so slot1=slot1+slot2+slot3,slot2=slot2+slot3+slot1,slot3=slot3+slot1+slot2,

It is not working, still got the sum of all slots in each slot

So I make some other test matrix to ckks.GenLinearTransform 

pass [1:[2,1,1,1] will get same value as input in each slot( 2 in value of slot0 is not working)
pass [1:[1,1,2,2] will get double value as input in each slot (1 invalue of slot0,1 is not working)

Would you give some tutorial of LinearTransform?

**Comment by Pro7ech** [comment]
Hi @extrame, 

You are correct, we should put a tutorial for the linear transform. What you have to give as input to `ckks.GenLinearTransform` are the non-zero diagonals of your plaintext matrix:
```
 0  1  2  3
|1, 1, 1, 1|         0: [1, 1, 1, 1]
|0, 1, 1, 0|    -> 1: [1, 1, 1, 0]
|0, 1, 0, 1|         2: [1, 0, 0, 0]
|0, 0, 1, 1|         3: [1, 0, 1, 1]
```

**Comment by extrame** [comment]
Ok, I got it.

But it seems still something wrong.

My plaintext matrix actual is :

```
0 1 2 3
|1, 0, 0, 0|          0: [1, 1, 1, 1]
|0, 1, 1, 1|    ->    1: [0, 1, 1, 0]
|0, 1, 1, 1|          2: [0, 1, 0, 1]
|0, 1, 1, 1|          3: [0, 0, 1, 1]
```

But what got is (only second slot is 0.5):

```
Input:
Level: 23 (logQ = 1303)
Scale: 2^45.000000
ValuesTest: (0.0000000000-0.0000000000i) (0.5000000000+0.0000000000i) (-0.0000000000+0.0000000000i) (0.0000000000+0.0000000000i)...

Output:
Level: 23 (logQ = 1303)
Scale: 2^45.000000
ValuesTest: (0.5000000000+0.0000000000i) (0.5000000000+0.0000000000i) (0.5000000000-0.0000000000i) (0.5000000000+0.0000000000i)...
```

According to the input matrix, I should got:
`ValuesTest: (0.0000000000+0.0000000000i) (0.5000000000+0.0000000000i) (0.5000000000-0.0000000000i) (0.5000000000+0.0000000000i)...`

**Comment by extrame** [comment]
Ok, I got the problem.

I GenLinearTransformBSGS by scale 1.

It seems that if the scale is too small, the difference in matrix vector will be ignored

So I change the scale of matrix to params.DefaultScale(). The result seems to be ok

```
ValuesTest: (0.0000000000+0.0000000000i) (0.5000000000-0.0000000000i) (0.0000000000+0.0000000000i) (-0.0000000000+0.0000000000i)...


Level: 23 (logQ = 1303)
Scale: 2^90.000000
ValuesTest: (0.0000000000+0.0000000000i) (0.5000000000+0.0000000000i) (0.5000000000+0.0000000000i) (0.5000000000+0.0000000000i)...
```

**Comment by Pro7ech** [comment]
My apologies, I made a mistake in the diagonalized matrix I gave you, I was tired, here is the correct one:

```
 0  1  2  3
|1, 1, 1, 1|         0: [1, 1, 0, 1]
|0, 1, 1, 0|    ->   1: [1, 1, 1, 0]
|0, 1, 0, 1|         2: [1, 0, 0, 0]
|0, 0, 1, 1|         3: [1, 0, 1, 1]
```

The `scale` input in `GenLinearTransform` scales the matrix by a constant, when encoding, it is not the CKKS scale. The encoded matrix is automatically scaled by the prime `q_i` that will be used for the rescaling, such that it is an exact rescaling and does not deviate the scale of the ciphertext from the default scale.
