### ISSUE TITLE
BFV bootstrapping?

### ISSUE THREAD

**Issue by lucaszanella** [tuneinsight/lattigo#176]
Are there plans to implement bootstrapping for BFV? I've seen that no one does it currently, maybe because it's too slow? What abou this new paper? https://eprint.iacr.org/2021/691.pdf

**Comment by Pro7ech** [comment]
Hello @lucaszanella, there is currently no short-term or long-term plan to add a bootstrapping for the BFV scheme. The approach described in the paper you linked could be an option, but it is painfully slow, as it does not support batching (the bootstrapping algorithm has to be evaluated on each coefficient individually).
