### ISSUE TITLE
What is a RingPQ?

### ISSUE THREAD

**Issue by lucaszanella** [tuneinsight/lattigo#177]
On all papers I've read, a public key or a ciphertext are both members of `Z_Q[X]/X^d+1`  where Q is a product of the RNS co-primes that form a 'rns basis'. Usually they use `t` for the plaintext modulus, which is the maximum value the plaintext coefficients can have. Also, Delta = Q/t dictates some stuff about rescaling and etc. I guess `Q` on LattiGo is the `Q` of the ring above, but is `P` the plaintext modulus? Why there is this ring PQ that stores a ring P and a ring Q?

```
// PolyQP represents a polynomial in the ring of polynomial modulo Q*P.
// This type is simply the union type between two ring.Poly, each one
// containing the modulus Q and P coefficients of that polynomial.
// The modulus Q represent the ciphertext modulus and the modulus P
// the special primes for the RNS decomposition during homomorphic
// operations involving keys.
```

From this comment it looks like the ring is `Z_{P*Q}[X]/X^d+1` which I've never seen before. Can you point me to a paper where it shows how this stuff works?

From here

```
The modulus Q represent the ciphertext modulus and the modulus P
the special primes for the RNS decomposition during homomorphic
operations involving keys.
```

it looks like ciphertexts are modulo Q, which is great, but there's this additional ring with P "the special primes for the RNS decomposition during homomorphic
operations involving keys.". 

I've played with lots of SEAL internals and they have no such concepts. There, Q is decomposed into coprimes (but they choose primes anyways), and represented in RNS form, and there's just one type of polynomial, the one from the ring `Z_Q[X]/X^d+1`. I get that you're using montgomery form, maybe this has to do with it?

Are you guys planning to release some PDF with the simple arithmetic? A nice 1 page overview would help a lot, at least in explaining what is the math behind, because Go is very easy to understand already. 

PS: I've read https://homomorphicencryption.org/wp-content/uploads/2020/12/wahc20_demo_christian.pdf but it does not show any of these math

**Comment by Pro7ech** [comment]
Hello @lucaszanella, Lattigo uses a hybrid key-switching (RNS basis decomposition combined with a rescaling) and its implementation is described in [this paper](https://eprint.iacr.org/2020/1203). In a nutshell, ciphertexts are mod Q and keys mod QP with the encrypted secret scaled by P. During the key-switch ciphertexts are extended to QP, the key-switch is done mod QP and then the result is divided by P, reducing the added error by that much.

As for SEAL, although not obvious, it also use the same kind of hybrid key-switching and their P is the last prime of the moduli chain. The difference between SEAL and Lattigo is that Lattigo allows the use of multiple primes for P.

**Comment by shuangyichen** [comment]
> 

Hi @Pro7ech , as you mentioned, SEAL uses the same kind of hybrid key-switching. Does it mean Lattigo and SEAL uses the same decomposition basis w? I am stuck at implementing multiparty relinearization key generation using SEAL. Thank you in advance.

**Comment by Pro7ech** [comment]
Hi @shuangyichen, I'm glad that you are implementing our work using SEAL. May I ask for what project it is?

**Comment by shuangyichen** [comment]
Hi @Pro7ech , it is a secure inference protocol based on Multi party HE. The implementation of the prior work we build upon uses SEAL. So we decide to implement MHE using SEAL.

**Comment by Pro7ech** [comment]
@shuangyichen Great :) 

The basis decomposition used by SEAL is a special case of our basis decomposition. It is equivalent to setting P to a single prime. In SEAL the last prime of the modulus chain is this special prime P.

**Comment by shuangyichen** [comment]
@Pro7ech Thanks for the information. Can I use the basis decomposition of SEAL to compute the relin-key share in round one $h_{0,i} = -u_i*a+s_i*w+e_{0,i}$?

**Comment by Pro7ech** [comment]
@shuangyichen, yes, like I said, the decomposition in SEAL is a special case of our more general decomposition.

**Comment by shuangyichen** [comment]
Thank you @Pro7ech , I successfully generate the collective relinearization key!
