### ISSUE TITLE
Index check is done after index access

### ISSUE THREAD

**Issue by ArmandoCasas** [tuneinsight/lattigo#189]
Hello,

I noticed the following lines in the `Rescale` function in `ckks/evaluator.go`:

```
	var nbRescales int
	// Divides the scale by each moduli of the modulus chain as long as the scale isn't smaller than minScale/2
	// or until the output Level() would be zero
	for ctOut.Scale/float64(ringQ.Modulus[ctIn.Level()-nbRescales]) >= minScale/2 && ctIn.Level()-nbRescales >= 0 {
		ctOut.Scale /= (float64(ringQ.Modulus[ctIn.Level()-nbRescales]))
		nbRescales++
	}
```
I imagine the for loop run conditions were intended the other way around to avoid an index out of range error:
`	for ctIn.Level()-nbRescales >= 0 && ctOut.Scale/float64(ringQ.Modulus[ctIn.Level()-nbRescales]) >= minScale/2 {`

**Comment by Pro7ech** [comment]
Hello @ArmandoCasas, 

Nice catch, thank you. We will certainly fix that!
