### ISSUE TITLE
Quick start for CKKS Average/InnerSum

### ISSUE THREAD

**Issue by cutukmirza** [tuneinsight/lattigo#194]
Is it possible to have an example on how to use the evaluator.average/innerSum functions, along with generating and using the necessary rotation keys?

**Comment by Pro7ech** [comment]
Hello @cutukmirza,

You can find such examples in the `ckks_test.go` file.

**Comment by cutukmirza** [comment]
Hello @Pro7ech, thank you for a quick reply and for your help!
