### ISSUE TITLE
The choice of plaintext modulus

### ISSUE THREAD

**Issue by xiezy0** [tuneinsight/lattigo#196]
How can I choose a bigger plaintext modulus than 64bit in BFV ？

**Comment by xiezy0** [comment]
Do you provide interface to represent the plaintext in the RNS domain？

**Comment by ChristianMct** [comment]
Not directly, unfortunately.

But you could create a custom `ring.Ring` object with your composite plaintext modulus and use its `SetCoefficientsBigint(coeffs []*big.Int, p1 *Poly)`  to turn your plaintext from []*big.Int to a single `ring.Poly` from which you can extract the sub-polynomials in RNS form.
