### ISSUE TITLE
Security Assumptions

### ISSUE THREAD

**Issue by nickshey** [tuneinsight/lattigo#197]
Does this implementation assume the use of a trusted setup, or do the clients perform setup with a trusted third party?

**Comment by Pro7ech** [comment]
Hello @nickshey, 

I assume you are referring to the multi-party key-generation protocols (`drlwe` package, on which are based the `dbfv` and `dckks` packages).  To securely generate shared keys, all that is needed for the clients are 1) a public authenticated channel and 2) to agree on a common reference string.

**Comment by ChristianMct** [comment]
The implementation of DBFV and DCKKS in Lattigo lets the clients generate their own keys (by using one of the `rlwe.KeyGenerator.GenSecretKey`methods). This locally generated key is the one to be provided as secret-key parameter in the protocol share generation methods. As such, there is no need for a trusted dealer of secret keys.

However, the protocols require the parties to have access to a public common reference string (CRS), which is often considered a trusted setup (the parties need to agree on a common seed/pseudorandom-sequence before the protocol starts) in the literature. Yet this one has nothing to do with the distribution of secret keys.
