### ISSUE TITLE
Example program about Multiplication Triples Generation?

### ISSUE THREAD

**Issue by bo-hub** [tuneinsight/lattigo#202]
Hi, I read the paper ["Multiparty Homomorphic Encryption from Ring-Learning-with-Errors"](https://eprint.iacr.org/2020/304). And I am curious about the implementation of the Multiplication Triples Generation function  in VI (D) section of the paper. Is there any example program discussing the function? I traveled the examples folder but have no finding. Thanks!

**Comment by ChristianMct** [comment]
Hi @bo-hub, 

You can find the multiplication triple generation program (for both the plain HE and MHE setting) in the following repository: [https://github.com/ldsec/lattigo-pets21](https://github.com/ldsec/lattigo-pets21).

The whole repository can be built as a docker image to run the experiments (see `README.md`)  and the triple generation program is located in the `apps/tpl` directory.

**Comment by bo-hub** [comment]
Got it! Thanks!
