### ISSUE TITLE
Question about threshold(or distributed ) decryption in DBFV

### ISSUE THREAD

**Issue by bo-hub** [tuneinsight/lattigo#205]
Hi, thanks for this wonderful project! I have a problem about the concept of threshold encryption shceme here. It seems that the MBFV(DBFV) scheme is a N-out-of-N threshold encryption scheme. By the concept of "threshold" , I believe it works like this, every party ` P_i` generates its own secret key `sk_i` , and use the CKGprotocol to generate the public key `pk`. Let's say a message `m` is encrypted undet `pk` and output a ciphertext `ct`. Now if we want to decrypt the ciphertext `ct`, we need every party use their own secret key `sk_i` to do a "partial decryption" on `ct` and get a message share  `decm_i`. Then a combiner use these message shares `decm_i` to do final decryption and get the final decryption message `m`. In the procedure , every party didn't leak their own share. That's what I think the "threshold encryption" means.   
But in the test program of dbfv , it seems we need first use a ideal secret key `sk0` to generate the decryptor `decryptorSk0` to do the decryption. If we do it in this way, in the end someone will have access to the ideal secret key and seems not the "threshold" meaning. Is there something I misunderstood?
https://github.com/tuneinsight/lattigo/blob/db8647b790d5d402a80191236ea19bb13d7104b3/dbfv/dbfv_test.go#L194

I extract some code from the `dbfv_test.go` file to show this procedure. My question is : is there a way we do not need to use the ideal secret key to do the decryption but use partial decryption and final combiner to do the decryption  so that both sk_i
 and ideal secret key will not be discloed?

```
package main

import (
	"fmt"

	"github.com/tuneinsight/lattigo/v3/bfv"
	"github.com/tuneinsight/lattigo/v3/dbfv"
	"github.com/tuneinsight/lattigo/v3/drlwe"
	"github.com/tuneinsight/lattigo/v3/ring"
	"github.com/tuneinsight/lattigo/v3/rlwe"
	"github.com/tuneinsight/lattigo/v3/utils"
)

var parties int = 3

type testContext struct {
	params bfv.Parameters

	// Polynomial degree
	n int

	// Polynomial contexts
	ringT *ring.Ring
	ringQ *ring.Ring
	ringP *ring.Ring

	prng utils.PRNG

	encoder bfv.Encoder

	sk0Shards []*rlwe.SecretKey
	sk0       *rlwe.SecretKey

	pk0 *rlwe.PublicKey

	encryptorPk0 bfv.Encryptor
	decryptorSk0 bfv.Decryptor

	crs            drlwe.CRS
	uniformSampler *ring.UniformSampler
}

func gentestContext(params bfv.Parameters) (tc *testContext, err error) {

	tc = new(testContext)

	tc.params = params

	tc.n = params.N()

	tc.ringT = params.RingT()
	tc.ringQ = params.RingQ()
	tc.ringP = params.RingP()

	prng, _ := utils.NewKeyedPRNG([]byte{'t', 'e', 's', 't'})
	tc.crs = prng
	tc.uniformSampler = ring.NewUniformSampler(prng, params.RingQ())

	tc.encoder = bfv.NewEncoder(tc.params)

	kgen := bfv.NewKeyGenerator(tc.params)

	// SecretKeys
	tc.sk0Shards = make([]*rlwe.SecretKey, parties)

	tc.sk0 = bfv.NewSecretKey(tc.params)

	ringQP, levelQ, levelP := params.RingQP(), params.QCount()-1, params.PCount()-1
	for j := 0; j < parties; j++ {
		tc.sk0Shards[j] = kgen.GenSecretKey()
		ringQP.AddLvl(levelQ, levelP, tc.sk0.Value, tc.sk0Shards[j].Value, tc.sk0.Value)
	}

	// Publickeys
	tc.pk0 = kgen.GenPublicKey(tc.sk0)

	tc.encryptorPk0 = bfv.NewEncryptor(tc.params, tc.pk0)
	tc.decryptorSk0 = bfv.NewDecryptor(tc.params, tc.sk0)

	return
}

func test() {
	defaultParams := bfv.DefaultParams // the default test runs for ring degree N=2^12, 2^13, 2^14, 2^15
	p := defaultParams[1]
	params, err := bfv.NewParametersFromLiteral(p)
	if err != nil {
		panic(err)
	}
	var tc *testContext
	if tc, err = gentestContext(params); err != nil {
		panic(err)
	}
	testPubkeygen(tc)
}

func testPubkeygen(tc *testContext) {
	sk0Shards := tc.sk0Shards
	decryptorSk0 := tc.decryptorSk0

	type Party struct {
		*dbfv.CKGProtocol
		s  *rlwe.SecretKey
		s1 *drlwe.CKGShare
	}
	ckgParties := make([]*Party, parties)
	for i := 0; i < parties; i++ {
		p := new(Party)
		p.CKGProtocol = dbfv.NewCKGProtocol(tc.params)
		p.s = sk0Shards[i]
		p.s1 = p.AllocateShare()
		ckgParties[i] = p
	}
	P0 := ckgParties[0]

	crp := P0.SampleCRP(tc.crs)

	// Checks that dbfv.CKGProtocol complies to the drlwe.CollectivePublicKeyGenerator interface
	var _ drlwe.CollectivePublicKeyGenerator = P0.CKGProtocol

	// Each party creates a new CKGProtocol instance
	for i, p := range ckgParties {
		p.GenShare(p.s, crp, p.s1)
		if i > 0 {
			P0.AggregateShare(p.s1, P0.s1, P0.s1)
		}
	}
	pk := bfv.NewPublicKey(tc.params)
	P0.GenPublicKey(P0.s1, crp, pk)
	// Verifies that decrypt((encryptp(collectiveSk, m), collectivePk) = m
	encryptorTest := bfv.NewEncryptor(tc.params, pk)

	coeffs, _, ciphertext := newTestVectors(tc, encryptorTest)

	verifyTestVectors(tc, decryptorSk0, coeffs, ciphertext)

}

func newTestVectors(tc *testContext, encryptor bfv.Encryptor) (coeffs []uint64, plaintext *bfv.Plaintext, ciphertext *bfv.Ciphertext) {

	prng, _ := utils.NewPRNG()
	uniformSampler := ring.NewUniformSampler(prng, tc.ringT)
	coeffsPol := uniformSampler.ReadNew()
	plaintext = bfv.NewPlaintext(tc.params)
	tc.encoder.Encode(coeffsPol.Coeffs[0], plaintext)
	ciphertext = encryptor.EncryptNew(plaintext)
	return coeffsPol.Coeffs[0], plaintext, ciphertext
}

func verifyTestVectors(tc *testContext, decryptor bfv.Decryptor, coeffs []uint64, ciphertext *bfv.Ciphertext) {
	flag := utils.EqualSliceUint64(coeffs, tc.encoder.DecodeUintNew(decryptor.DecryptNew(ciphertext)))
	if flag {
		fmt.Println("Verification Passed!")
	} else {
		fmt.Println("Verification Failed!")
	}
}

func main() {
	test()
}
```

**Comment by Pro7ech** [comment]
Hi @bo-hub, 

The tests in Lattigo are written to test only one thing at a time and not more (so that if something goes wrong, we know where the issue is). This is why we use the "ideal" secret to test if the creation of the public-key works, since this test purpose is to examine the output of the CKG protocol and make sure that its output is correct. 

Regarding the collective decryption of a ciphertext encrypted using the collective public key `[pk[0]*u + m + e, pk[1]*u + e]`, each party will computes a decryption share `[a*sk_i + e]` that can freely be disclosed since it is a valid RLWE sample. 

However, you still have to be careful with the case where someone would ask twice the decryption for the same ciphertext, as publishing `[-as + e]` and `[-as + e']` leads to an insecure instance. In this case you need to make sure that you sample the same error.

**Comment by bo-hub** [comment]
@Pro7ech .Thanks for your quick reply! I got why use the "ideal" secret key here. I'll try if I can made an example program about the "threshold" decryption here.

**Comment by bo-hub** [comment]
@Pro7ech . Hi, I am trying to formally write the threshold decryption process now. And I got stuck to combine the  decryption share to get the final decrypted message. Is there any API interface to do with combine function ?  Here is what I tried:
```
        // Decryption by secret key share
	tempPlaintext := make([]*bfv.Plaintext, parties)
	for j := 0; j < parties; j++ {
		// decrypt by sk0 shards
		decryptorShared := bfv.NewDecryptor(params, sk0Shards[j])
		tempPlaintext[j] = decryptorShared.DecryptNew(ciphertext)
	}
	//TODO : add tempPlaintext together to get the final decryption
```
The total code is 
```
package main

import (
	"fmt"

	"github.com/tuneinsight/lattigo/v3/bfv"
	"github.com/tuneinsight/lattigo/v3/dbfv"
	"github.com/tuneinsight/lattigo/v3/drlwe"
	"github.com/tuneinsight/lattigo/v3/ring"
	"github.com/tuneinsight/lattigo/v3/rlwe"
	"github.com/tuneinsight/lattigo/v3/utils"
)

var parties int = 3

func test() {
	fmt.Println("Begin test")
	defaultParams := bfv.DefaultParams // the default test runs for ring degree N=2^12, 2^13, 2^14, 2^15
	p := defaultParams[1]
	params, err := bfv.NewParametersFromLiteral(p)
	if err != nil {
		panic(err)
	}
	tcringT := params.RingT()
	encoder := bfv.NewEncoder(params)

	prng, _ := utils.NewKeyedPRNG([]byte{'t', 'e', 's', 't'})
	crs := prng

	// generation of secret parties
	kgen := bfv.NewKeyGenerator(params)

	// SecretKeys shares
	sk0Shards := make([]*rlwe.SecretKey, parties)

	// ideal secret key -> sk0
	sk0 := bfv.NewSecretKey(params)

	ringQP, levelQ, levelP := params.RingQP(), params.QCount()-1, params.PCount()-1
	for j := 0; j < parties; j++ {
		// gen parties' secret key
		sk0Shards[j] = kgen.GenSecretKey()
		// aggregate secret key to sk0
		ringQP.AddLvl(levelQ, levelP, sk0.Value, sk0Shards[j].Value, sk0.Value)
	}

	type Party struct {
		*dbfv.CKGProtocol
		s *rlwe.SecretKey
		// public key share
		s1 *drlwe.CKGShare
	}
	ckgParties := make([]*Party, parties)

	for i := 0; i < parties; i++ {
		p := new(Party)
		p.CKGProtocol = dbfv.NewCKGProtocol(params)
		p.s = sk0Shards[i]

		// allocate memory
		p.s1 = p.AllocateShare()
		ckgParties[i] = p
	}
	// party0
	P0 := ckgParties[0]

	// sample common reference polynomial from common reference string
	crp := P0.SampleCRP(crs)

	// Checks that dbfv.CKGProtocol complies to the drlwe.CollectivePublicKeyGenerator interface
	var _ drlwe.CollectivePublicKeyGenerator = P0.CKGProtocol

	// Each party creates a new CKGProtocol instance
	for i, p := range ckgParties {
		// generate public key share
		p.GenShare(p.s, crp, p.s1)
		if i > 0 {
			// then aggregate them to P0.s1
			P0.AggregateShare(p.s1, P0.s1, P0.s1)
		}
	}

	// allocate memory with 0
	pk := bfv.NewPublicKey(params)
	P0.GenPublicKey(P0.s1, crp, pk)

	// Encryption by pk
	encryptorTest := bfv.NewEncryptor(params, pk)
	prng1, _ := utils.NewPRNG()
	uniformSampler1 := ring.NewUniformSampler(prng1, tcringT)
	coeffsPol := uniformSampler1.ReadNew()
	coeffs := coeffsPol.Coeffs[0]
	plaintext := bfv.NewPlaintext(params)
	encoder.Encode(coeffsPol.Coeffs[0], plaintext)
	ciphertext := encryptorTest.EncryptNew(plaintext)

	// Decryption by ideal secret key sk0
	decryptorSk0 := bfv.NewDecryptor(params, sk0)
	flag := utils.EqualSliceUint64(coeffs, encoder.DecodeUintNew(decryptorSk0.DecryptNew(ciphertext)))
	fmt.Println(flag)

	// Decryption by secret key share
	tempPlaintext := make([]*bfv.Plaintext, parties)
	for j := 0; j < parties; j++ {
		// decrypt by sk0 shards
		decryptorShared := bfv.NewDecryptor(params, sk0Shards[j])
		tempPlaintext[j] = decryptorShared.DecryptNew(ciphertext)
	}
	//TODO : add tempPlaintext together to get the final decryption

}

func main() {
	test()
}

```

**Comment by Pro7ech** [comment]
If you use the `rlwe.Decryptor` to generate the shares, then you need to make sure that the ciphertext format is (0, c1), because the decryptor evaluates the ciphertext at the secret key (i.e. it computes `ct(sk) = <(c0, c1, ...,), (1, sk, sk^2, ...)>`).

This is one way to do it. However, the library provides a protocol to do the shared decryption: `dbfv.CKSProtocol` which is a wrapper of the `drlwe.CKSProtocol,` which enables to re-encrypt a ciphertext from a shared secret to a different shared secret. If you put your target shared secret to be the zero key, the it acts as a decryption protocol. 

You start by allocating your  `drlwe.CKSShare` using the `AllocateShare` method, then generate the share using the `GenShare` method, then aggregate the shares using the `AggregateShare` (not that the share comply to the MarshalBinary interface), and finally key-switch your ciphertext using the  `KeySwitch` method.

Each step is fully documented in the `drlwe/keyswtich_sk.go`.

**Comment by bo-hub** [comment]
Hi, @Pro7ech . Thanks for your patience! I checked the `keyswitch_sk.go`  and continued read the paper Multiparty Homomorphic Encryption from Ring-Learning-with-Errors (last time got stuck in KeyGen phase and didn't read the remain parts). Finally I think I got the idea behind lattigo dbfv. It seems that the decryption protocol mainly used the `keyswitch` protocol. Like when the secret key `s'` is known by the party , `keywitch` is used.  If only a public key is known, use `PubKeySwitch` protocol. And followed by the example in `dbfv/pir/main.go` , I figured out the procedure mostly. But I still have one thing confused.

In this line (cksphase part) of the  `dbfv/pir/main.go` file 
https://github.com/tuneinsight/lattigo/blob/593ae1a7111b35befe0b8b00284531ce9a92edcc/examples/dbfv/pir/main.go#L208-L210
We want to generate cks share of each party to do keywitch. But it seems `Party 0` didn't contribute his share. I know later `Party 0 ` will use his `sk0` to decrypt . But why he need not contribute his share in this cks share generation phase?

**Comment by Pro7ech** [comment]
In the example, `Party 0` is the external party, during the decryption phase (but not during the key generation phase). So all peers, except `Party 0` participate to the decryption protocol, homomorphically removing their mask. The output ciphertext of the key-switch protocol is encrypted under the secret-share of `Party 0`. So to decrypt it, he only has to use the regular decryption protocol, giving as key his secret-share.

**Comment by bo-hub** [comment]
Thanks for your explanation! Finally I got this!

**Comment by bo-hub** [comment]
> If you use the `rlwe.Decryptor` to generate the shares, then you need to make sure that the ciphertext format is (0, c1), because the decryptor evaluates the ciphertext at the secret key (i.e. it computes `ct(sk) = <(c0, c1, c2,...), (1, sk, sk^2,...)>`).
> 
> This is one way to do it. However, the library provides a protocol to do the shared decryption: `dbfv.CKSProtocol` which is a wrapper of the `drlwe.CKSProtocol` and enables to re-encrypt a ciphertext from a shared secret to a different shared secret. If you put your target shared secret to be the zero key, it acts as a decryption protocol.
> 
> You start by allocating your `drlwe.CKSShare` using `AllocateShare` , then generate the share using `GenShare` , then aggregate the shares using the `AggregateShare` (not that the shares comply to the `MarshalBinary` interface), and finally key-switch your ciphertext using `KeySwitch`.
> 
> Although the protocol outputs a ciphertext, in your case since you do a decryption you can switch the ciphertext to a plaintext type with `pt := &bfv.Plaintext{Plaintext:&rlwe.Plaintext{Value:ciphertext.Value[0]}}` after the protocol.
> 
> Each step is fully documented in the `drlwe/keyswtich_sk.go`.

@Pro7ech Hi, I am trying to follow the idea to use `rlwe.Decrypto` to generate Decryption shares. As you mentioned, Given a ciphertext `ct = (ct0,ct1)`. First I should generate a ciphertext copy as `ct_temp=(0,ct1)` , then for each secret key share `sk_i`, I do a partial decryption `ct_temp(sk_i) = <(0,ct1),(1,sk_i)> = ct1*sk_i` , Then I should do a combine decryption share phase like  `ct0 + Sum(ct1*sk_i)`.  
There are two step I am not sure how to do it in Lattigo. First , how to set a cipher `ct_temp = (0,ct1)`? i.e set the first cipher to be zero. Second , how to sum the partial decryption share together?
Thanks!

**Comment by Pro7ech** [comment]
Hi @bo-hub, 

I suggest that you use the `drlwe.CKSProtocol` instead of trying to implement the partial decryption with the `rlwe.Decryptor`, because the `drlwe.CKSProtocol` has been designed for exactly what you are trying to do.

**Comment by Pro7ech** [comment]
Everything is built using the `ring` package. You can take a look at the code of `drlwe.Decryptor`, it should show you how to implement your own decryptor if you want to do so.

I agree that paper documenting the inner working of Lattigo would come a long way, and it is has been on the back of my mind for quite some time. But I wasn't able to prioritize it since there is a lot of development going on. Eventually it will be done. However, in the mean time, the godoc can help a lot, each public method comes with some documentation.

**Comment by bo-hub** [comment]
@Pro7ech Thanks a lot! Your team is so generous for spending so much time to maintain such a wonderful library and share it with community!
