### ISSUE TITLE
How can i print data of a Ciphertext using Lattigo ?

### ISSUE THREAD

**Issue by Fishermanljh** [tuneinsight/lattigo#206]

**Comment by Pro7ech** [comment]
You can access the k-th coefficient of the j-th modulus of the i-th element of a ciphertext with `ct.Value[i].Coeffs[j][k]`

**Comment by Pro7ech** [comment]
You can't get a single large float, but you can get an 1-dimensional polynomial with coefficient of type *big.Int with
```
coeffs_bigint := make([]*big.Int, params.N())
for i := range coeffs_bigint:
    coeffs_bigint[i] = new(big.Int)
params.RingQ().PolyToBigintCenteredLvl(ct.Level(), ct.Value[i], 1, coeffs_bigint)
```

**Comment by Fishermanljh** [comment]
I see. Thanks for your reply again, and it addressed my concern.
