### ISSUE TITLE
Serialization of  ciphertext or publickey shares?

### ISSUE THREAD

**Issue by bo-hub** [tuneinsight/lattigo#210]
Hi! How to do serialization in Lattigo?  What's the typical way to write some objects to file?
I find a method called `MarshalBinary()` which can transform objects to byte and `UnmarshalBinary()` the other direction. Then maybe I can use something like `os.WriteFile()` to write the byte array to file. But is there some method directly write some objects to file and then transform? 
Thanks!

**Comment by ChristianMct** [comment]
The `BinaryMarshaler` and `BinaryUnmarshaler` interfaces of the standard `encoding` package is the only supported way for now.  But we plan to add stream serializers in the future to avoid the two-step process that you mentioned.

**Comment by ChristianMct** [comment]
Yes, `os.WriteFile` is probably the most concise way of writing bytes in a not-yet-opened file.
