### ISSUE TITLE
Some confusion caused by float64 division precision loss

### ISSUE THREAD

**Issue by Li-Yanbin** [tuneinsight/lattigo#211]
Hi,
When I changed  the input coeffs array in func testExtendBasis of ring_test.go from random values to 0 to N-1, it produced an unexpected output. I looked closely at the related functions, found that the problem might be related to the float64 division used in func reconstructRNS of ring_basis_extension.go. Because of the precision loss of float64 division, v[i] might be one less than it should be. So I tried to use v[j] = uint64(vi[j] + EpsilonFloat64) instead of v[j]=uint64(vi[j]) (0<=j<=7) to pass the test. 
I don't know if I got it wrong, or it might affect the rest part.

**Comment by Pro7ech** [comment]
Hi Li-Yanbin, 

I believe the only place where an exact basis extension is needed is during the scale down step of the BFV decoding, the other operations can tolerate errors in the correction factor v. In fact, the original implementation of the full-RNS CKKS does not even computes this correction factor, as it only introduces a small additive noise in practice.

**Comment by Li-Yanbin** [comment]
Hi,
I think the The imprecision of v[i] value causes the imprecision of index of vtimesqmodp in Func multSum. And it appears to be a random error and happens many times. From the test result, I do not think this error is minor.
<img width="554" alt="截屏2022-05-25 09 17 23" src="https://user-images.githubusercontent.com/65152528/170159212-3a781a1a-2668-4588-bdcb-806a7fe92f7f.png">
<img width="550" alt="截屏2022-05-25 09 17 47" src="https://user-images.githubusercontent.com/65152528/170159229-de190753-51c8-47be-a0a1-e47e28a77364.png">
