### ISSUE TITLE
Bootstrapping with BFV scheme

### ISSUE THREAD

**Issue by aasimmd** [tuneinsight/lattigo#217]
Is bootstrapping only possible with CKSS scheme?

**Comment by Pro7ech** [comment]
The centralized bootstrapping is possible with the BFV scheme, but it is not practical and there is no plan to add it to the library. However, there is the collective bootstrapping, in the dbfv package that provides the same functionality.

**Comment by aasimmd** [comment]
Thanks a lot! Could you point me to the exact function in dbfv or any docs regarding collective bootstrapping in dbfv?

**Comment by Pro7ech** [comment]
- `dbfv/refresh.go`: collective bootstrapping
- `dbfv/transform.go`: collective bootstrapping with a linear transform

**Comment by aasimmd** [comment]
Thanks a lot!
