### ISSUE TITLE
Storing the ciphertext

### ISSUE THREAD

**Issue by cutukmirza** [tuneinsight/lattigo#218]
Hi,

This is a question, not really an issue, but here goes. 

How would one go about storing the encrypted vectors into a database? I am talking in practical terms; store, then later read (possibly query) and do some operations on the stored values with Lattigo. Would it be enough to store the actual ciphertext, but then how would I reconstruct the ciphertext object that I need for operations? In my research so far, I have only encountered CryptDB, which was impressive at the time, but I couldn't find any other attempts at solving this problem, using the CKKS scheme for example. Do you perhaps know of any other research that could help me?

Thank you for your help!

Best,
Mirza

**Comment by Pro7ech** [comment]
You can use the `.MarshalBinary()` interface to convert ciphertexts (as well as parameters or keys) in `[]bytes`, and then stores those bytes in a database. Then the element can be loaded from the bytes with `xx.UnmarshalBinary(bytes)`
