### ISSUE TITLE
Which of the parameters can be made public?

### ISSUE THREAD

**Issue by aasimmd** [tuneinsight/lattigo#220]
In context of the dbfv psi example,
The party struct : 
```
type party struct {
	sk         *rlwe.SecretKey
	rlkEphemSk *rlwe.SecretKey

	ckgShare    *drlwe.CKGShare
	rkgShareOne *drlwe.RKGShare
	rkgShareTwo *drlwe.RKGShare
	pcksShare   *drlwe.PCKSShare

	input []uint64
}
```
Here **ckgShare**, **rkgShareOne** and **rkgShareTwo** are generated using the secret key and crp; Do we need to create private channels between parties to aggregate the shares and generate the pk and rlk?
By this I mean are the select parameters mentioned above are private to the parties or can they be publicly disclosed.

**Comment by ChristianMct** [comment]
`ckgShare`, `rkgShareOne` and `rkgShareTwo` above can be publicly disclosed (see [2020/304](https://eprint.iacr.org/2020/304) for more information about the CKG and RKG protocols).

**Comment by aasimmd** [comment]
Thanks a lot!
