### ISSUE TITLE
Sorting the ciphertext

### ISSUE THREAD

**Issue by cutukmirza** [tuneinsight/lattigo#223]
This is more of a question than an issue, but since I couldn't find a solution myself I would like to ask whether there are any ciphertext sorting capabilities of the Lattigo library, and if not, how do you advise one to go about it using Lattigo resources (or some other if necessary). 

Thank you!

Kind regards

**Comment by Pro7ech** [comment]
Could you elaborate on what you mean by 'sorting ciphertexts'?

**Comment by cutukmirza** [comment]
Hello @Pro7ech,

Thank you for responding. What I mean is that if I have an array of unsorted values, and I encrypt them, is it currently possible to sort the array while it is encrypted? If not, do you have any suggestions on how to go about it?

Thank you very much, great work you're doing with Lattigo!

**Comment by Pro7ech** [comment]
Well, it's simple (in principle) but difficult (in practice): you have to do encrypted comparisons. 

An encrypted comparison takes the inputs En(a, b) and returns Enc(a) if a >= b else Enc(b). 

This can for example be done with f(a, b) = a + ReLU(b-a). If (b-a) is negative, then it means that a > b, and thus ReLU(b-a) = 0, so f(a, b) = a, else ReLU(b-a) = b-a and f(a, b) = a + (b-a) = b.

An other way is to evaluate f(a, b) = 0.5 * (a + b + sign(b-a) * (b-a)), with sign(b-a) = 1 if b > a, 0 if b = a and -1 if b < a.

Depending on your schemes (exact or approximate) implementing these non-linear functions will be or less difficult. 

Lattigo does not have pre-implemented comparison circuit, so you will have to make up on your own.

**Comment by cutukmirza** [comment]
Alright, thank you very much for your help, I'll get to work then.

Have a nice day!
