### ISSUE TITLE
The Error of encryption algorithms in different goroutine？

### ISSUE THREAD

**Issue by xiezy0** [tuneinsight/lattigo#226]
When I put many Encryption Algorithm to goroutines, I get the following error. So how to use multi-threading to Encrypt data without using a Mutex?
```go
plainSlice := make([]*ckks.Plaintext, 0)
cipherSlice := make([]*ckks.Ciphertext, 0)
var wg sync.WaitGroup
wg.Add(5)
for i := 0; i < 5; i++ {
	var cipher *ckks.Ciphertext
	cipherSlice = append(cipherSlice, cipher)
	text := encoder.EncodeSlotsNew([]float64{55}, params.MaxLevel(), params.DefaultScale(), params.LogSlots())
	plainSlice = append(plainSlice, text)
}
for i := 0; i < 5; i++ {
	go func(num int) {
		cipherSlice[num] = encryptor.EncryptNew(plainSlice[num])
		wg.Done()
	}(i)
}
wg.Wait()
for i := 0; i < 5; i++ {
	result := decryptor.DecryptNew(cipherSlice[i])
	output := encoder.DecodeSlots(result, params.LogSlots())
	fmt.Println(output[0])
}
```
![image](https://user-images.githubusercontent.com/52877446/182030080-4b29e53e-acd6-4ad1-844f-58097b3fdfbb.png)

**Comment by Pro7ech** [comment]
Lattigo is not thread safe. You have to call `.ShallowCopy` on elements like `Encryptor` or `Evaluator` to create a threadsafe copy of the target element, that will re-allocate its internal buffers. Then for each go routine after the first one you use a different shallow copy.

**Comment by xiezy0** [comment]
> Lattigo is not thread safe. You have to call `.ShallowCopy()` on elements like `Encryptor` or `Evaluator` to create a threadsafe copy of the target element, that will re-allocate its internal buffers. Then for each go routine after the first one you use a different shallow copy.

Ok, thankyou! I will have a try.
