### ISSUE TITLE
comparable performance to state-of-the-art C++ libraries

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#227]
Hi,

It's said to have comparable performance to state-of-the-art C++ libraries.
Is there any document for this comparison and metrics for the comparison?

BR

**Comment by Pro7ech** [comment]
Hi,

This recent works compares multiples libraries, including Lattigo:  [New Insights into Fully Homomorphic Encryption
Libraries via Standardized Benchmarks](https://eprint.iacr.org/2022/425.pdf)

**Comment by macknight** [comment]
> Hi,
> 
> This recent works compares multiples libraries, including Lattigo: [New Insights into Fully Homomorphic Encryption Libraries via Standardized Benchmarks](https://eprint.iacr.org/2022/425.pdf)

thanks
