### ISSUE TITLE
What is RNS

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#228]
Hi,
What's RNS? It's an abbreviation.
And how to define it as "full"? Like what are the elements of a "Full RNS"?
BR

**Comment by Pro7ech** [comment]
RNS means "Residue Number System" which is the the Chinese Remainder Theorem representation of integers. "Full RNS" means that all computations are done in the RNS domain, without having to go back to the positional domain (standard representation). You can read [A Full RNS Variant of
Approximate Homomorphic Encryption](https://eprint.iacr.org/2018/931.pdf) for more details.

**Comment by macknight** [comment]
> RNS means "Residue Number System" which is the the Chinese Remainder Theorem representation of integers. "Full RNS" means that all computations are done in the RNS domain, without having to go back to the positional domain (standard representation). You can read [A Full RNS Variant of Approximate Homomorphic Encryption](https://eprint.iacr.org/2018/931.pdf) for more details.

great, thanks
