### ISSUE TITLE
Calculating homomorphic sqrt

### ISSUE THREAD

**Issue by cutukmirza** [tuneinsight/lattigo#235]
Hey guys,

I am trying to calculate the sqrt of a ciphertext of **real** numbers, but I am having some problems with the results not being consistent and or inaccurate. The truth is I am not that familiar with Chebyshev Approximation and I have a feeling I am not setting some parameters properly or there is something else I am not seeing. Could you please take a look?

Here is the code I am currently using:

```
func sqrt_real(x float64) float64 {
	return math.Sqrt(x)
}
// func sqrt(x complex128) complex128 {
// 	return complex(math.Sqrt(real(x)), 0)
// }
func main() {

	params, err := ckks.NewParametersFromLiteral(ckks.PN14QP438)
	if err != nil {
		panic(err)
	}

	kgen := ckks.NewKeyGenerator(params)
	sk, pk := kgen.GenKeyPair()
	rlk := kgen.GenRelinearizationKey(sk, 2)
	rotKeyRep := kgen.GenRotationKeysForRotations(params.RotationsForInnerSumLog(1, 8192), false, sk)

	encoder := ckks.NewEncoder(params)
	encryptor := ckks.NewEncryptor(params, pk)
	decryptor := ckks.NewDecryptor(params, sk)
	evaluator := ckks.NewEvaluator(params, rlwe.EvaluationKey{Rlk: rlk, Rtks: rotKeyRep})

	data := make([]float64, 0)

	for j := 0; j < 8192; j++ {
		data = append(data, 4.0)
	}

	p1 := encoder.EncodeNew(data, params.MaxLevel(), params.DefaultScale(), params.LogSlots())
	c1 := encryptor.EncryptNew(p1)

	// slots index
	slotsIndex := make(map[int][]int)
	idxF := make([]int, params.Slots())
	for i := 0; i < params.Slots(); i++ {
		idxF[i] = i
	}
	slotsIndex[0] = idxF

	// calculate square root
	sqrt_cheby := ckks.Approximate(sqrt_real, 1.5, 2.5, 33)
	if c1, err = evaluator.EvaluatePolyVector(c1, []*ckks.Polynomial{sqrt_cheby}, encoder, slotsIndex, c1.Scale); err != nil {
		panic(err)
	}

	// decrypt
	tmp := encoder.Decode(decryptor.DecryptNew(c1), params.LogSlots())

	valuesTest := make([]float64, len(tmp))
	for i := range tmp {
		valuesTest[i] = real(tmp[i])
	}
	fmt.Println("decrypted ", valuesTest[0])}
```

Thank you!

**Comment by Pro7ech** [comment]
Hi @cutukmirza, you need to change the basis (normalize) the ciphertext before evaluating a Chebyshev polynomial. This is not automatically done by the evaluator to let the user include it for free in previous steps of the circuit (it is a linear transformation). You'll find what you need to do exactly in the godoc of EvaluatePoly.

**Comment by cutukmirza** [comment]
Hi @Pro7ech, just found it. Thanks a lot!

**Comment by cutukmirza** [comment]
Hi @Pro7ech,

I did the normalization step, but now I am getting super small values as the result. Should I change the base again to get the real result, and how would I go about doing that?

**Comment by Pro7ech** [comment]
@cutukmirza you don't need to do anything after the polynomial evaluation. Have you checked that your input values fall into your approximation interval ? In your example file you encrypt a vector of 4s but the approximation interval is [1.5, 2.5].

**Comment by cutukmirza** [comment]
I changed the approximation interval values a:=-8 and b:=8, at first, but then I was receiving 0 as the result of the approximation. I checked the ckks.Approximation function, and it says:
```
// Approximate computes a Chebyshev approximation of the input function, **for the range [-a, b]** of degree degree.
// function.(type) can be either func(complex128)complex128 or func(float64)float64
// To be used in conjunction with the function EvaluateCheby
```
This part **for the range [-a, b]** was not clear to me, so I changed the approximation interval values to just a:=8 and b:=8, and now I am getting sqrt(4.0) = 2.82, which is not bad, but not yet optimal, what can I tweak to get it a bit more precise?

I am trying to follow the polyeval example for ckks, and there for the normalization part it is coded as:
```
evaluator.MultByConst(ciphertext, 2/(b-a), ciphertext)
evaluator.AddConst(ciphertext, (-a-b)/(b-a), ciphertext)
```
Which differs a bit from the the formula in the polyeval description:
```
// ct' = (2/(b-a)) * (ct + (-a-b)/(b-a))
```
Should it be the other way around, or am I not seeing something?

**Comment by Pro7ech** [comment]
This is because the square root of a negative number is undefined for real numbers so math.Sqrt(x) will return NAN. If you replace it by cmplx.Sqrt it should work but will return complex numbers. Else you need to define your interval as [a=0, b].

**Comment by cutukmirza** [comment]
@Pro7ech My God, what a stupid mistake x). I fixed it right now and it works like a charm.

Thank you!
