### ISSUE TITLE
/examples/ckks/euler/main.go  issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#237]
Hi,
![image](https://user-images.githubusercontent.com/754293/184884128-5ae26fa8-465b-494c-a84a-b16cd13f20cd.png)

I'm using go run main.go in path /examples/ckks/euler but it has above error when running inside Windows WSL ubuntu.

BR

**Comment by Pro7ech** [comment]
Hi @macknight, this seems to be an issue that isn't related to Lattigo but to your installation of Go. Is there any reason you are trying to run the example through Windows WSL Ubuntu and not directly on Windows?

**Comment by macknight** [comment]
> Hi @macknight, this seems to be an issue that isn't related to Lattigo but to your installation of Go. Is there any reason you are trying to run the example through Windows WSL Ubuntu and not directly on Windows?

Yeah, I prefer to use linux system. So I tried in WSL, it couldn't work.
So I changed to use directly inside windows, it works.
Maybe the installation mapping is not correct in WSL. Anyway it works in windows now.

Thanks

BR
