### ISSUE TITLE
Outdated/Missing package specific README.md

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#239]
Hi,
![image](https://user-images.githubusercontent.com/754293/184893432-e6099224-3508-4a8d-b856-bfbfe615c706.png)

![image](https://user-images.githubusercontent.com/754293/184893619-0598a0a6-3b5f-4d56-addb-4f9f2d2a8318.png)

ckks/README.md and bfv/README.md have many images missing.
Could you have a look?

BR

**Comment by Pro7ech** [comment]
@macknight The image are rendering find on my side, both on Firefox and Chrome. Have you made sure you don't have a web browser plugin blocking something?

Regardless, we haven't taken a look at those README for quite a while and they definitely need a new make over, and some package are missing them, so I updated this issue accordingly

**Comment by macknight** [comment]
> 

oh right, I change to use Firefox, and the images show.
So maybe my chrome has some problem.

BR
