### ISSUE TITLE
import github.com/tuneinsight/lattigo/v3/ckks Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#243]
Hi,
![image](https://user-images.githubusercontent.com/754293/185104290-14b93056-0719-48d3-be48-ec91ae82c808.png)
what does this v3/ckks mean? The branch name or tag name or others?
![image](https://user-images.githubusercontent.com/754293/185104437-a96940eb-421b-42c1-98de-e214d227d81a.png)

It seems not the url link.
![image](https://user-images.githubusercontent.com/754293/185104525-35a65512-6cc8-4505-a99d-85baf214769a.png)

BR

**Comment by Pro7ech** [comment]
This is how versioning works in Go. v3 refers to any version of the form v3.x.x.
