### ISSUE TITLE
e^x Math Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#244]
Hi,
I couldn't quite understand this:
![image](https://user-images.githubusercontent.com/754293/185124160-69b1463a-8804-4009-bc65-d1db287315e0.png)
Is it pure math knowledge? Where could I find the relative math?

BR

**Comment by Pro7ech** [comment]
These are the coefficient of the Taylor expansion of e^x, a new polynomial is created and then homomorphically evaluated on the ciphertext.

**Comment by macknight** [comment]
> These are the coefficient of the Taylor expansion of e^x, a new polynomial is created and then homomorphically evaluated on the ciphertext.

Thanks for your reply. I got it.
