### ISSUE TITLE
Package name meaning Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#245]
Hi,
![image](https://user-images.githubusercontent.com/754293/185132365-ccc1e0c2-00b9-4835-b607-3264c1102bb9.png)
How about the meaning of euler? is it meaning classic code? 
I only know euler is a mathematician.

BR

**Comment by Pro7ech** [comment]
Each package has its own small description. You can find the godoc of the library, as well as the package description in https://pkg.go.dev/github.com/lca1/lattigo
