### ISSUE TITLE
PN14QP438CI Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#246]
Hi,
![image](https://user-images.githubusercontent.com/754293/185150785-d3dabc14-53b8-415c-812f-3dbfb9dc2a1d.png)

for this specific number 0x2000000a0001, its binary format is 1000000000000000000000000010100000000000000001 which has 46 binary digits. So why the comment says it's 45 bit? Is the comment wrong? it should be "// 45 +" ?

Another questions is for levels, is it the elements' number of Q or LogQ of PN14QP438CI object?
What's the meaning of P or logP of PN14QP438CI object? Any rules to set this P or logP?
![image](https://user-images.githubusercontent.com/754293/185154411-18ebe9f7-836f-491d-842f-c3f7f718b091.png)

BR

**Comment by Pro7ech** [comment]
If you take the round(log in base 2) of those numbers you will get the expected number.
