### ISSUE TITLE
LogN and LogSlot Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#247]
Hi,
I've read through the file ckks/params.go, and found that all PN objects have logN= LogSlot or Logn = 1 + LogSlot.
Why they have such relations? What's the differences between logN= LogSlot and Logn = 1 + LogSlot?

BR

**Comment by Pro7ech** [comment]
With CKKS to N/2 slots can be encoded on a N coefficient polynomial, this is because complex numbers are encoded.
