### ISSUE TITLE
What's H

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#248]
Hi,
I see some code like:
	fmt.Printf("CKKS parameters: logN = %d, logSlots = %d, H(%d; %d), logQP = %d, levels = %d, scale= 2^%f, sigma = %f \n", params.LogN(), params.LogSlots(), params.HammingWeight(), btpParams.EphemeralSecretWeight, params.LogQP(), params.QCount(), math.Log2(params.DefaultScale()), params.Sigma())

What's H?  And what are params.HammingWeight(), btpParams.EphemeralSecretWeight?

BR

**Comment by Pro7ech** [comment]
`H` is the number of non-zero coefficient in the secret. Please read the documentation of the related structure for more information.
