### ISSUE TITLE
bits issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#250]
Hi,
![image](https://user-images.githubusercontent.com/754293/185278614-cfaadd81-c9d2-487d-bec7-9d8fb1f7c0f7.png)
May I know why here the comment says it's 65.0000116961637 bits?
0x800004001=100000000000000000000100000000000001
0x40002001=1000000000000000010000000000001
they totally have 64 bits, and how to get65.0000116961637 bits which even has decimal part?

BR

**Comment by Pro7ech** [comment]
If you take `log(0x800004001 * 0x40002001, 2)` you will get `65.0000116961637`
