### ISSUE TITLE
Lattigo Resources Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#251]
Hi,
Are there any tutorial videos or webseminar videos of Lattigo?
And any online community of lattigo like in stackoverflow or slack channel?
Looks like lattigo code has not enough comments or the comments are a little too professional, it spends much time for me to use and understand what the code is doing.

BR

**Comment by Pro7ech** [comment]
There is no easy shortcut to homomorphic encryption. You can join the FHE discord (https://discord.gg/wnEjJDxN) to ask more general questions about FHE (and theere is a channel for Lattigo). Getting familiar with the field first will help you a lot understanding what the capabilities of R-LWE based HE are and how they are mapped in Lattigo.

**Comment by macknight** [comment]
Thanks

BR
