### ISSUE TITLE
Param issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#258]
Hi,
https://github.com/tuneinsight/lattigo/blob/master/examples/ckks/advanced/lut/main.go
![image](https://user-images.githubusercontent.com/754293/187830222-4cb4bde2-0857-4046-8981-baf1a42082e3.png)

why 65.0000116961637 bits?

0x800004001 stands for 100000000000000000000100000000000001 (36bits)
0x40002001 stands for 1000000000000000010000000000001 (31bits)
total bits is 64 bits, so why does the comment say  65.0000116961637 bits?

BR

**Comment by Pro7ech** [comment]
See https://github.com/tuneinsight/lattigo/issues/250
