### ISSUE TITLE
security parameters

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#259]
![image](https://user-images.githubusercontent.com/754293/188300533-1ab76ed2-f452-4bad-861d-2664a00c92e9.png)
Hi,

LogN = 18, what could be the proper value for pameters like LogQ?
Looks like the standard PDF doesn't have this LogQ when LogN=18.
![image](https://user-images.githubusercontent.com/754293/188300576-301aeeed-3341-45e0-a566-86fc76735be8.png)

BR

**Comment by macknight** [comment]
wait, looks like the proper LogQ is doubled when LogN increases by 1?
{18, 7048, 3.2} should also be good for 128-bit security?

By the way, what does here 128-bit security stand for? which object has 128 bits?

BR

**Comment by Pro7ech** [comment]
Hi @macknight, 

We provide default parameters which are aligned with the security standard and we will not give direct security advices for parameters that deviate from these default parameters. If you want create your own parameters, you should be aware of the security implications. You can estimate the security of your custom parameters with the lattice estimator (https://github.com/malb/lattice-estimator).

**Comment by macknight** [comment]
> Hi @macknight,
> 
> We provide default parameters which are aligned with the security standard and we will not give direct security advices for parameters that deviate from these default parameters. If you want create your own parameters, you should be aware of the security implications. You can estimate the security of your custom parameters with the lattice estimator (https://github.com/malb/lattice-estimator).
> 
> 128-bit actually stands for 2^128 ring operations

Other questions about this "128-bit actually stands for 2^128 ring operations".
1. 2^128 ring operations are different from the concept of the ring degree, right?
2. what are these  2^128 ring operations in detail? addition, multiplication?
3. 128-bit security, does it mean if anyone has a powerful computer with enough CPU, RAM and Disk which is able to comput 2^128 ring operations is able to crack this 128-bit security?


BR

**Comment by Pro7ech** [comment]
1.\2. A ring operations is any operation in the ring (e.g. add, mul, inversion). The ring refers to the polynomial ring used by the scheme.

3. Yes, but it is as of nowday, and for the many years to come, not even concern. Even if everyone on earth joined hands and tried to do it, it would take an absurde amount of times the age of the universe.

**Comment by macknight** [comment]
> 1.\2. A ring operations is any operation in the ring (e.g. add, mul, inversion). The ring refers to the polynomial ring used by the scheme.
> 
> 2^128 is an absurdly large number. Even if everyone on earth joined hands and tried to do it (with today's technology) they wouldn't succeed before the heat death of the universe (that's exaggerated but you get the point).

fantastic reply which is very vivid
