### ISSUE TITLE
MaxLogN=17 issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#260]
![image](https://user-images.githubusercontent.com/754293/188301469-35c30be6-4ac4-4ae3-8224-06db4649995a.png)
Hi,
Is this MaxLogN=17 a limitation of FHE itself or lattigo?

Also another question is I used LogN=18, why the error msg says I'm using LogN=19?
![image](https://user-images.githubusercontent.com/754293/188301560-8e72bb98-a526-4484-9d79-faa2137cc5b0.png)

BR

**Comment by Pro7ech** [comment]
You can remove this hard cap manually by changing the constant. 

It says 19 because the actual size of the ring is 2^19 when using the Conjugate Invariant ring (even if in practice only 2^18 coefficients are required).
