### ISSUE TITLE
multi-party issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#261]
Hi,
I see that lattigo supports multi-party FHE, right?
so what paper(s) does this multi-party feature of lattigo refer to?
this one? On-the-Fly Multiparty Computation on the Cloud via Multikey Fully Homomorphic Encryption.pdf
https://dl.acm.org/doi/abs/10.1145/2213977.2214086?casa_token=E579lEPNg9wAAAAA:2ts7OuFbLpcSzFiGk_miL7fn7Q4P0Ab0wbyFYLWX-fF7ZbAaDKBYMg8GYh5apPihx3XAjdi2zuyP

![image](https://user-images.githubusercontent.com/754293/188483087-af80d1df-30fc-425f-8bd1-4be8e45df983.png)

BR

**Comment by Pro7ech** [comment]
It is reference [4.](https://eprint.iacr.org/2020/304) in the README.md
