### ISSUE TITLE
no example/dckks folder

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#262]
Hi,
![image](https://user-images.githubusercontent.com/754293/188484531-f3cb0e16-0bb3-4668-a677-057a240abae0.png)
is there a folder of dckks here while bfv has its dbfv folder? 
Does this mean the example of dckks would have the same process of dbfv example? so there's no need to write a specific dckks folder, right?

BR

**Comment by ChristianMct** [comment]
It is correct. The `dckks` package implements a threshold variant of CKKS, which has the same interface as the threshold BFV scheme so there is no example specifically for `dckks` yet.
