### ISSUE TITLE
DBVF issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#264]
Hi,
I see here two example of DBVF. This looks likem to be set operations, not number addition or multiplication operations.
![image](https://user-images.githubusercontent.com/754293/188485247-9ef22ae6-5ac3-45bd-8906-4e27850d269c.png)

So for scenarios where I have different integer numbers encrypted with different public keys, could I be ABLE to compute to get an encrypted summation, and then decrypt(by some kind of protocol) to get this summation cleartext number?

BR

**Comment by Pro7ech** [comment]
Lattigo does not support multi-key yet, operation are only valid between ciphertexts encrypted under the same secret (which can be secret shared between the parties).

The examples provided do use addition, multiplication and rotation.
