### ISSUE TITLE
SMC Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#265]
![image](https://user-images.githubusercontent.com/754293/188575382-0e8fc0a0-6e7a-4a95-96e9-2023d3c4d1f5.png)

Hi,
What does SMC stand for? I search but find a lot of answers, not sure which is exact.

BR

**Comment by ChristianMct** [comment]
It stands for "Secure Multiparty Computation", or "SMPC", if you prefer.
