### ISSUE TITLE
Other issues of security of FHE schemes and lattigo lib

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#266]
Dear Lattigo Team,
For the default security params(tuples), we know that we have 128-bit security which means addition/multiplication/other operations over a polynomial ring. 

1. how to know that it's 128-bit security? why isn't the security level 127 bits? I mean how to calculate this 128-bit out?

2. the current FHE security is based on the hardness of Ring-LWE. so is this 128-bit security just an instance/example of this hardness of Ring-LWE? Or do they mean different perspective of security of the FHE schemes?

3. we know that 128-bit is 2^128 which means a huge amount of operations and computations, so it's hard to attack. But is it safe under quantum attacks? I heard that google seems to have developed quantum computers to do computations very quickly and in paralell.  So could we say that 128-bit security could be secure enough under quantum attacks too?

BR

**Comment by Pro7ech** [comment]
We provide the library as is, with default parameter sets which are 128-bit secure, but will not give any security related advice. The security of custom parameter sets can be estimated using the [lattice estimator](https://github.com/malb/lattice-estimator). For anything else related to security, please see the [homomorphic encryption standard document](https://homomorphicencryption.org/standard/)
