### ISSUE TITLE
bfv: how to know the remaining noise budget before decrypting?

### ISSUE THREAD

**Issue by fumin** [tuneinsight/lattigo#270]
I am coming from microsoft/seal, and as I understand it, BFV requires its noise budget to not be depleted before decrypting, or else garbage will be returned.

The closest thing I can find is [DecryptAndPrintError](https://pkg.go.dev/github.com/ldsec/lattigo/v2/bfv#DecryptAndPrintError).
Could you confirm that this function corresponds to the `invariant_noise_budget` in microsoft/seal?
If so, would it be possible for this function to directly return the noise, instead of just printing them out?

Since a relinearization is required when the noise budge is depleted, wouldn't [Evaluator](https://pkg.go.dev/github.com/ldsec/lattigo/v2/bfv#Evaluator) need to provide an `Undo` function, so that we can revert the operation, relinearize, then redo the operation correctly?

**Comment by Pro7ech** [comment]
@fumin 

Yes this function does compute the same noise than SEAL (|dec(ct) - delta * m|_infty). 

I'll improve it to only require the decryptor and the ciphertext, and return the noise info as variables.

It will be added in the v4.0.0

What do you mean by "relinearization is required when the noise budge is depleted" ?

**Comment by fumin** [comment]
@Pro7ech Thanks for your confirmation, and I look forward to the next release!

By "relinearize when noise budget is depleted", I mean the impossibility to decrypt the ciphertext due to excessive noise contained in it, as described in

https://github.com/microsoft/SEAL/blob/main/native/examples/1_bfv_basics.cpp#L330

I was wondering what do we do in this case? In Microsoft/seal, they simply rerun the circuit from the very beginning, but relinearize right before the noise overwhelms. I was thinking we could be smarter by simply undoing the operation, instead of recomputing from scratch.
Does this optimization make sense? If not, what's the recommended way of determining when to relinearize?

**Comment by Pro7ech** [comment]
Oh I see. I believe this SEAL example is to show that there are multiple ways to compute the same circuit, with some ways leading to a smaller noise growth.

In practice you will usually always want to relinearize after a multiplication. 

If you do not have enough noise budget for your circuit, the only solution is to use larger parameters.

**Comment by fumin** [comment]
I see, thanks @Pro7ech for your explanation. Also, thanks for releasing this great library, too. : )
