### ISSUE TITLE
BSGS Linear transform: different results with different values of bsgsratio

### ISSUE THREAD

**Issue by Thity** [tuneinsight/lattigo#271]
Compute the following multiplication with bsgsRatio of 2.0 and 10.0 consecutively
```
|1 1|  x  |2|
|1 1|     |2|
```
Result with bsgsRatio of 10.0 (correct) :
```
|4|
|4|
```
Result with bsgsRatio of 2.0 (wrong) :
```
|4|
|2|
```
[main.go.txt](https://github.com/tuneinsight/lattigo/files/9585479/main.go.txt)

**Comment by Pro7ech** [comment]
@Thity thank you for reporting this bug, I'll look into it and see what is going on.

**Comment by Pro7ech** [comment]
@Thity the issues comes from the diagonals which are not given as vectors of length `params.Slots()`. I'll add a fix that first copies the values on a vector of the correct size.
