### ISSUE TITLE
dckks rtgphase issue, not able to run correctly. How to write a valid rtgphase function for a combine ciphertext of all parties where the combined ciphertext has a size of a non power of 2

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#272]
Hi,
the dckks example psi, it doesn't have a runnable function called rtgphase which is to geneate the collective rotation key.
So after calculating the result ciphertext based on each parties' ciphertext. How could I calculate the sum of all the elements of this result ciphertext?
I mean this:
say we have c1 from party1, c2 from party2, c3 from party3, c4 from party4.
then we calcuate the multitask and get result ciphertext which is R, and R has 10 elements([0,1,.....,9]), how could I calcuate the sume of these 10 elements of R. (Note that 10 is not a power of 2)

My code could run but the result is not correct. How could I solve this?
![image](https://user-images.githubusercontent.com/754293/190849273-8f353b4f-c39f-4eb8-a9a1-e50af4637643.png)
CKKS Average of encRes should also be 0.182019, but it's a wrong value.

func **main**() {
......
rotk := rtgphase(params, crs, P)
evaluator := ckks.NewEvaluator(params, rlwe.EvaluationKey{Rlk: rlk, Rtks: rotk})
.....
after get R from c1,c2,c3,c4
.......
evaluator.InnerSumLog(R, 1, 100, R) // calculate sum of R's 100 elements
encOut.Scale *= float64(100)// calculate average of R's 100 elements
.........
}

//generate collective rotation key
func **rtgphase**(params ckks.Parameters, crs utils.PRNG, P []*party) *rlwe.RotationKeySet {
	l := log.New(os.Stderr, "", 0)

	l.Println("> RTG Phase")

	rtg := dckks.NewRotKGProtocol(params) // Rotation key generation
	rtgCombined := rtg.AllocateShare()

	for _, pi := range P {
		pi.rtgShare = rtg.AllocateShare()
	}

	crp := rtg.SampleCRP(crs)
	//get rotations
	ks := params.RotationsForInnerSumLog(1, len(P[0].input))
	//get galEls from rotations, refer to "GenRotationKeysForRotations"
	//not includeConjugate
	galEls := make([]uint64, len(ks), len(ks)+1)
	for i, k := range ks {
		galEls[i] = params.GaloisElementForColumnRotationBy(k)
	}
	//get rks
	rotKeySet := ckks.NewRotationKeySet(params, galEls)

	//rest elapsedRTGParty
	elapsedRTGParty = 0
	elapsedRTGCloud = runTimed(func() {
		for _, galEl := range galEls {
			for _, pi := range P {
				elapsedRTGParty += runTimedParty(func() {
					rtg.GenShare(pi.sk, galEl, crp, pi.rtgShare)
				}, 1)
				rtg.AggregateShare(pi.rtgShare, rtgCombined, rtgCombined)
			}
			rtg.GenRotationKey(rtgCombined, crp, rotKeySet.Keys[galEl])
		}
	})
	elapsedRTGCloud -= elapsedRTGParty

	return rotKeySet
}

BR

**Comment by Pro7ech** [comment]
Hi @macknight,

We currently do not have any example for dckks in the library. If you are taking the example provided by the external pull-request #180, I'm afraid we will not be able to provide support since this code is not from our team and not part of the library.

**Comment by macknight** [comment]
> 

thanks, I'll try to do that.

**Comment by wonderit** [comment]
Hi @macknight, 

The example of generating collective rotation key (rtkphase) can be found in `examples/dckks/pir`. Hope the link below could help. 
https://github.com/wonderit/lattigo/blob/d81abbe8970b30e1a2816fc46bfeca24b18d75cb/examples/dckks/pir/main.go#L326
