### ISSUE TITLE
pcksPhase issue in dckks(dbfv)'s example(could it turn the encOut back to a ciphertext which is using collective public key?)

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#273]
Hi,
I know that through key switching, I could get encOut which is encrypted by tpk, and could decrypted by tsk.
encOut = pcksPhase(params, tpk, encRes, P) // turn to tpk

But could I switch it back for usage?
tmpOut = pcksPhase(params, pk, encOut, P) // turn to pk(collective public key)
evaluator.Add(ciphertext_of_one_party, tmpOut, tmpOut2)  // is it OK ??
finalOut = pcksPhase(params, tpk, encOut2, P) // turn to tpk // is it OK ??

encoder.Decode(decryptor.DecryptNew(finalOut), params.LogSlots()) // will finalOut be correctly decrypted and the result correct?

BR

**Comment by Pro7ech** [comment]
If you want to switch back from pk_target to pk_collective, you need to know the associated secret to pk_target. This is trivial to do since this is not a collective key: just have the owner of pk_target decrypt and re-encrypt using pk_collective.

Does this answer your question?

**Comment by macknight** [comment]
> 

Thanks for your reply.
so, basicly there is only one method: firstly owner of tpk needs to decrypt and then uses cpk to encrypt.
There's no way to directly turn it back from tpk to cpk encrypted data without decrypting it first.  Right?

BR

**Comment by ChristianMct** [comment]
This is correct. Switching ciphertexts from an input secret-keys to a target secret-key always requires the knowledge of the input secret-key (note that there would be no semantic security if it wasn't the case). It does not require the knowledge of the output secret-key, as the corresponding public key suffices (with the PCKS protocol).

So if the input secret-key is collectively known (MHE setting), the CKS/PCKS protocols must be used for re-encryption. If the input secret-key is owned by a single party (plain HE setting), this boils down to decrypting and re-encrypting to the target key locally.
