### ISSUE TITLE
Question about BFV params

### ISSUE THREAD

**Issue by jrylost** [tuneinsight/lattigo#276]
In BFV README, the param P  follows the constraint ![image](https://user-images.githubusercontent.com/34121887/190931499-7639a7d0-5534-48eb-b6ad-f4d21b0e5eb2.png) by a small margin (~20 bits), but I don't understand in

PN12QP109 = ParametersLiteral{
LogN:  12,
T:     65537,
Q:     []uint64{0x7ffffec001, 0x8000016001}, // 39 + 39 bits
P:     []uint64{0x40002001},                 // 30 bits
Sigma: rlwe.DefaultSigma,
}

Is PQ>Q^2? Or P here only represents "using one more small coprime modulus than equation Q"? But why P exceeds 20 bits?

**Comment by ChristianMct** [comment]
There is indeed a mismatch between the documentation and the implementation here.

The current BFV implementation now handles the multiplication modulus transparently, without the need to specify it as a parameter. Hence, there is a mismatch between the definition of `P` in this documentation (the modulus extension for multiplication) and the modulus `P` in the `ParametersLiteral` type (the general modulus extension for key-switching). 

Thanks for the feedback.

**Comment by Pro7ech** [comment]
#379
