### ISSUE TITLE
ckks's   InnerSum and InnerSumLog

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#278]
Hi,
I see that InnerSum and InnerSumLog, but could quite understand this comment. Does "the number of rotations" refer to the len(rotations) or each value of rotations? And 'n' keys refer to what key, rotation keys? What does "HW(n)" stands for?
Could you give an example to show when to use InnerSumLog or InnerSum?

// This method is faster than InnerSumLog when the number of rotations is small but uses 'n' keys instead of log(n) + HW(n).
func (eval *evaluator) InnerSum(ctIn *Ciphertext, batchSize, n int, ctOut *Ciphertext) 

BR

**Comment by ChristianMct** [comment]
> Does "the number of rotations" refer to the len(rotations) or each value of rotations?
It refers to the number of distinct rotations "amounts" you need for the operation, i.e. `len(params.RotationsForInnerSumLog(batch, n))`, i.e. the number of rotation keys that you need to compute it.

> And 'n' keys refer to what key, rotation keys?
`n` is the number of sub-batches of size `batchSize`. In simple cases when you have no sub-batching (`batchSize = 1`) this is the number of slots.

> What does "HW(n)" stands for?
This stands for "Hamming Weight of n".

> Could you give an example to show when to use InnerSumLog or InnerSum?
You would typically use `InnerSumLog` when `n` is large. E.g., if you encrypt single vectors of size 2^12: `batchSize=1`, `n=2^12`, `InnerSum` would require `2^12` rotation-keys which may be a lot, whereas `InnerSumLog` requires only 13 rotations keys.

Hope this helps.
