### ISSUE TITLE
[drlwe]: CKS/PCKS does not properly resizes the level of the output ciphertext to the one of the input ciphertext

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#279]
Hi,
Would you please have a look at below code, it's almost using example/dbfv/psi/main.go, I only changed a little in evalPhase function and add some print code in main. Youc could see evalPhase function.
When I use power function to calculate x -> x^2, the result is wrong.
But when I use mul&relinearize to calculate x -> x^2, the result is correct.
I don't understand why it's wrong when using power function.

BR

**Comment by Pro7ech** [comment]
@macknight Can you produce a small and self-contained `main.go` that reproduces the error?

**Comment by macknight** [comment]
> @macknight Can you produce a small and self-contained `main.go` that reproduces the error?
> 
> Regardless, we plan to discontinue the `.Power(*)` method, because it's functionality is now provided by the `PolynomialBasis` struct. You can use it like this to get your powers :
> 
> ```
> pb := ckks.NewPolynomialBasis(ct, ckks.Monomial)
> pb.GenPower(power, false, params.DefaultScale(), evaluator)
> ctPower := pb.Value[power].CopyNew()
> ```

OK, I'll try the new method. 

And I've updated my post with the zip file including the main.go (I put the file here: example/dckks/psi/main.go for run), would you try that for testing?

BR

**Comment by Pro7ech** [comment]
@macknight I've found the issue, it doesn't come from the evaluation phase, it comes from the level of the ciphertext that you allocate during the pcks phase. You should allocate a ciphertext of the level of the input ciphertext. However, this mistake should have been caught by the protocol. I'll add checks to ensure that you'd get an appropriate error if the levels do not match.

To fix your code change it to 

`encOut = ckks.NewCiphertext(params, 1, encRes.Level(), params.DefaultScale())`
