### ISSUE TITLE
[ring/operations] ring.Shift may modify its input operand

### ISSUE THREAD

**Issue by s-chtl** [tuneinsight/lattigo#280]
Hi, 

It would seem there is an issue with the Shift function that re-writes on p1.

```
tmp := ring.NewPoly()
ringQ.Shift(c, i, tmp)
ringQ.Ntt(tmp, tmp)
```

modifies c

**Comment by Pro7ech** [comment]
@s-chtl I couldn't find the method `.Shift` in the package `ringqp`. Could you please produce a small main that reproduces your error?
