### ISSUE TITLE
ckks: panic EOF

### ISSUE THREAD

**Issue by Fishermanljh** [tuneinsight/lattigo#284]
panic: EOF

goroutine 1 [running]:
github.com/tuneinsight/lattigo/v3/utils.(*KeyedPRNG).Clock(0xc0002088e8, {0xc0014b2000?, 0xc000070280?, 0x0?})
        C:/Users/e/go/pkg/mod/github.com/tuneinsight/lattigo/v3@v3.0.5/utils/prng.go:58 +0x57
github.com/tuneinsight/lattigo/v3/ring.(*UniformSampler).ReadLvl(0xc0005927b0, 0x1, 0xc00210c500)
        C:/Users/e/go/pkg/mod/github.com/tuneinsight/lattigo/v3@v3.0.5/ring/ring_sampler_uniform.go:93 +0x136
github.com/tuneinsight/lattigo/v3/rlwe.(*pkEncryptor).Encrypt(0xc000592810, 0xc001258118, 0xc00037e5d0)
        C:/Users/e/go/pkg/mod/github.com/tuneinsight/lattigo/v3@v3.0.5/rlwe/encryptor.go:111 +0x6f
github.com/tuneinsight/lattigo/v3/ckks.(*encryptor).EncryptNew(0xc00044a280, 0xc00004ba40)
        C:/Users/e/go/pkg/mod/github.com/tuneinsight/lattigo/v3@v3.0.5/ckks/encryptor.go:40 +0xe9
main.main()
        C:/Users/e/GolandProjects/awesomeProject3/ckks-pariler-crt/141-ckks.go:1049 +0x8f02

**Comment by Fishermanljh** [comment]
I run encryption, encrypted computation, and decryption for different data with the same pk and sk many times, and this error arises.
For instance：
			plaintext0 := encoder.EncodeNew([]float64{v1}, params.MaxLevel(), params.DefaultScale(), params.LogSlots())
			ciphertext0 := encryptor.EncryptNew(plaintext0)
			rand.Seed(time.Now().UnixNano())
			a0 := 1 + (rand.Float64()-0.5)/math.Sqrt(math.Sqrt(float64(t)))
			plaintext0_2 := decryptor.DecryptNew(evaluator.MultByConstNew(evaluator.AddConstNew(ciphertext0, v2), a0))
			result0 := encoder.Decode(plaintext0_2, params.LogSlots())
then:
			plaintext1 := encoder.EncodeNew([]float64{v3}, params.MaxLevel(), params.DefaultScale(), params.LogSlots())
			ciphertext1 := encryptor.EncryptNew(plaintext1)
			rand.Seed(time.Now().UnixNano())
			a1 := 1 + (rand.Float64()-0.5)/math.Sqrt(math.Sqrt(float64(t)))
			plaintext1_2 := decryptor.DecryptNew(evaluator.MultByConstNew(evaluator.AddConstNew(ciphertext1, v3), a1))
			result1 := encoder.Decode(plaintext1_2, params.LogSlots())
what is the possible reason for this error?

**Comment by Pro7ech** [comment]
Hi @Fishermanljh, could you please produce a small and self-contaiend `main.go` that reproduces the error so that we can look into it?

**Comment by Pro7ech** [comment]
Closed due to 7 days of inactivity from OP.
