### ISSUE TITLE
party number limitation of dbfv/psi

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#287]
Hi,
https://github.com/tuneinsight/lattigo/blob/master/examples/dbfv/psi/main.go

![image](https://user-images.githubusercontent.com/754293/194745654-9f3dce1a-7ab5-40bd-bf4a-5f2116a1c244.png)

what does this mean by // Largest for n=8192: 512 parties?

the largest value is 8192 or 512?
And why we have limitations for N? could I change the limitation?

BR

**Comment by Pro7ech** [comment]
See issue #269
