### ISSUE TITLE
[test] Some benchmark tests are failing

### ISSUE THREAD

**Issue by romainbou** [tuneinsight/lattigo#304]
Running the complete bench test suite with `go test -timeout=0 -bench=. ./...`, I noticed that some are failing.

List of failing benchmark tests:
- https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/bgv/bgv_benchmark_test.go#L155
- https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/bgv/bgv_benchmark_test.go#L208
- https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/ckks/ckks_benchmarks_test.go#L206
- https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/rlwe/rlwe_benchmark_test.go#L54
- https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/rlwe/rlwe_benchmark_test.go#L61

Moreover, two tests are intentionally skipped, I was wondering if they should remain this way?
- https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/dckks/dckks_benchmark_test.go#L94
- https://github.com/tuneinsight/lattigo/blob/adf762375670e412bab261cd7ffff9ca03777ad5/dckks/dckks_benchmark_test.go#L156

**Comment by Pro7ech** [comment]
@romainbou I'll fix the failing tests. Regarding the benchmarks in `dckks`, I'll discuss with @ChristianMct if we should enable them for insecure parameters.
