### ISSUE TITLE
issue of IDASH PRIVACY & SECURITY WORKSHOP 2022

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#310]
Hi,
I'd like to know that will the code of IDASH PRIVACY & SECURITY WORKSHOP 2022 - secure genome analysis competition be public?
And how could I find the video of the presentation? Looks like Indiana University account is need to access the video?

BR

**Comment by Pro7ech** [comment]
Hi @macknight, this question is unrelated to Lattigo. Please contact Tune Insight directly https://tuneinsight.com/.
