### ISSUE TITLE
Does Lattigo have a documentation ?

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#314]
Hi,
Is there any help document or vidoes for developer who studies Lattigo?
There are 3 README.md files and the code itself, but it still requires a deep understanding of Lattigo to use it smoothly.

BR

**Comment by ChristianMct** [comment]
Hi,

Lattigo follows the Go-style documentation (godoc) and you can access it in HTML form here:
[https://pkg.go.dev/github.com/tuneinsight/lattigo/v4](https://pkg.go.dev/github.com/tuneinsight/lattigo/v4#section-documentation).

We agree that this is not the best way of getting started with the library and we are working on a more gentle "Getting Started" document. There is also going to be a update on the godoc and READMEs in the beginning of 2023. So documentation is coming...
