### ISSUE TITLE
CKKS LUT Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#315]
Hi,
https://github.com/tuneinsight/lattigo/blob/master/examples/ckks/advanced/lut/main.go
Why do we need Key-switching N12 to N11?
Any more explanations or docs on this LUT task for non-linear functions? I don't quite understand the whole process of LUT.

And is it OK to use LUT to calculate piecewise functions?
like f(x) =  x^2 + 3*x , when x >3
            =  x - 5 , when x <= 3

BR

**Comment by Pro7ech** [comment]
Yes you can use LUT to evaluate piece-wise functions.

As for how LUT work, this is a subject that is too broad ans complex to explain here. However Lattigo implementation is based on this work https://eprint.iacr.org/2021/691 and this work is a good introduction into LUT https://eprint.iacr.org/2021/1402.

The reason the ring degree is switched from N12 to N11 is for efficiency reasons.
