### ISSUE TITLE
CKKS params Issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#316]
Hi,
Is there any error here? https://github.com/tuneinsight/lattigo/tree/master/ckks
![image](https://user-images.githubusercontent.com/754293/207834306-e6d25547-090a-415e-a4c4-6d0524407496.png)

_we pre-multiply the plaintext by d^(1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5)) + x^5_
should be
_we pre-multiply the plaintext by d^(-1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5))x^3 + x^5_

And when evaluating _a + b/(d^(1/5))x + c/(d^(3/5))x^3 + x^5_ , why could it be faster when using 
![image](https://user-images.githubusercontent.com/754293/207838846-9561053b-34f6-460f-ace0-942bd279fbc4.png)
The action of squeezing two multiplications in a single level, what does it actually do?
Does it mean regarding (x*x) * x  as a entire one action although it uses two multiplication?

BR

**Comment by ChristianMct** [comment]
> we pre-multiply the plaintext by d^(1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5)) + x^5
> should be
> we pre-multiply the plaintext by d^(-1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5))x^3 + x^5

Yes, this is correct.

> The action of squeezing two multiplications in a single level, what does it actually do?
It means that you perform two multiplications and rescale only once. For the example above, you have an input scale of 30 bits and the next level in the chain is a modulus of ~60 bits. So after the two multiplications, the scale is ~90 bits and the rescale brings it back to ~30 bits. The point is that this is faster than having a chain of ~30 bits moduli and rescaling after every multiplication.

**Comment by macknight** [comment]
> > we pre-multiply the plaintext by d^(1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5)) + x^5
> > should be
> > we pre-multiply the plaintext by d^(-1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5))x^3 + x^5
> 
> Yes, this is correct.
> 
> > The action of squeezing two multiplications in a single level, what does it actually do?
> 
> It means that you perform two multiplications and rescale only once. For the example above, you have an input scale of 30 bits and the next level in the chain is a modulus of ~60 bits. So after the two multiplications, the scale is ~90 bits and the rescale brings it back to ~30 bits. The point is that this is faster than having a chain of ~30 bits moduli and rescaling after every multiplication.

Hi,
for 2 multiplication, base 30bits scale + 30bitsscale(first multiplication) + 30bits(second multiplication) = 90bits scale after the two multiplication, right?

And then the next modulus is 60bits, so 90-60=30bits (this is the broght back bits)
this is quicker than normal because the there's only one homomorphic rescaling opertion.
Am I getting your point?

BR

**Comment by ChristianMct** [comment]
> for 2 multiplication, base 30bits scale + 30bitsscale(first multiplication) + 30bits(second multiplication) = 90bits scale after the two multiplication, right?
> 
> And then the next modulus is 60bits, so 90-60=30bits (this is the broght back bits)
> this is quicker than normal because the there's only one homomorphic rescaling opertion.
> Am I correct?

Yes. This is what I meant in my previous message.

**Comment by ChristianMct** [comment]
> I can understand this. But why should I firstly pre-multiply the plaintext by d^(-1/5)? Seems irrelevant to the squeezing operation?

This is because you want the scale to match the powers of x for each of the products.
