### ISSUE TITLE
128-bit security

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#317]
Hi,
What is the simple meaning of 128-bit security?
Dose it mean if there's a 128-bit computer, the security of homomorphic encryption will be broken?

BR

**Comment by ChristianMct** [comment]
This question is not about Lattigo. Please do not use this channel to ask general questions about cryptography or even FHE. 

Short answer: 128-bit security does not mean that a 128-bit computer can break the encryption. However, what a 128-bit security level concretely represents is a much more complex topic as the definition depends on computational assumptions.  

For what regards the security level for Lattigo, 128-bit security means that we comply with the [standard's](https://homomorphicencryption.org/standard/) criteria for 128-bit security level and therefore (implicitly) with their definition of bit-security.
