### ISSUE TITLE
The precision concept in Lattigo

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#318]
Hi,
![image](https://user-images.githubusercontent.com/754293/207873516-2e6eb074-e54f-4fe0-a2e4-589bec61ffad.png)

What's the precision concept in Lattigo?

For example, a fix-point number 12.345
which part does the precision stand for？
12.345 as a whole?
or 345 which is after radix point?
or 12 which is before radix point?

BR

**Comment by Pro7ech** [comment]
Précision refers to the number of bits after the decimal
