### ISSUE TITLE
squeezing multiplication issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#319]
Hi,

> we pre-multiply the plaintext by d^(1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5)) + x^5
> should be
> we pre-multiply the plaintext by d^(-1/5) and evaluate a + b/(d^(1/5))x + c/(d^(3/5))x^3 + x^5
> 
> Yes, this is correct.
> 
> The action of squeezing two multiplications in a single level, what does it actually do?
> 
> It means that you perform two multiplications and rescale only once. For the example above, you have an input scale of 30 bits and the next level in the chain is a modulus of ~60 bits. So after the two multiplications, the scale is ~90 bits and the rescale brings it back to ~30 bits. The point is that this is faster than having a chain of ~30 bits moduli and rescaling after every multiplication.

I can understand this. But why should I firstly  pre-multiply the plaintext by d^(-1/5)? Seems irrelevant to the squeezing operation?
BR

**Comment by ChristianMct** [comment]
This question is a follow up from issue #316.
