### ISSUE TITLE
Issue of Pow2Base

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#323]
Hi,

	// RLWE parameters of the LUT
	// N=1024, Q=0x7fff801 -> 2^131
	paramsLUT, err := rlwe.NewParametersFromLiteral(rlwe.ParametersLiteral{
		LogN:     10,
		Q:        []uint64{0x7fff801},
		Pow2Base: 6,
	})

What does this mean by Pow2Base: 6? pow(2, 6)? What's the rules to assign values to Pow2Base?
And why it's 2^131? How this 131 is calculated out?
When should I use Pow2Base and when shouldn't I use Pow2Base?

BR

**Comment by Pro7ech** [comment]
PowBase2 is the power of two decomposition during the key-switching. See Supplementary Material 2. of eprint/2020/1023

The value to assign depends on the application and noise. The smaller it is, the smaller the noise but the heavier the keys are and the key-switching is. Please read the reference above to see why and how it behaves. If using an auxiliary modulus P, it can be omitted (set to 0). 

2^131 is the estimated security computed using https://github.com/malb/lattice-estimator

**Comment by macknight** [comment]
> 

Thanks, I'll have a look.

**Comment by macknight** [comment]
> 
PowBase2 is the power of two decomposition during the key-switching. See Supplementary Material 2. of
https://eprint.iacr.org/2020/1023.pdf
