### ISSUE TITLE
lattice-estimator issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#325]
Hi,
Here the paramsN12 has 128-bit secure.
![image](https://user-images.githubusercontent.com/754293/208873035-0bf07020-03c8-4f28-b531-f163cc499cfe.png)

I want to confirm is the way below correct when you calculate to get this 128-bit secure?
![image](https://user-images.githubusercontent.com/754293/208872642-7494d7cc-06ea-40e4-8084-848a9948f061.png)
here the result is:
rop: ≈2^130.8
Does this mean the comments in the lattigo code which says it has 128-bit secure?

BR

**Comment by Pro7ech** [comment]
The code in lattigo says `>128` which means greater than 128. 

For how to properly use the Lattice estimator, please ask the owners directly.

**Comment by macknight** [comment]
From Ben (Zama) — Today at 9:59 PM
Hi @macknight, looking at the issue you have linked (#325), you can use a similar parameter set but I would change  Xe so that your parameter set looks like:

params = LWE.Parameters(n = 2**12, q = 2**103, Xs = ND.UniformMod(3), Xe = ND.DiscreteGaussian(3.2))

from here, since it looks like Lattigo are following the assumptions from https://eprint.iacr.org/2019/939, you can call:

LWE.estimate(params, red_cost_model = RC.BDGL16)

to retrieve a security estimate. If you have any more questions feel free to follow up 🙂 .

**Comment by macknight** [comment]
From Ben (Zama) — Today at 10:06 PM
I would take them all in to consideration -- as an example (using a Kyber parameter set since it's quicker):

LWE.estimate(schemes.Kyber512, red_cost_model = RC.BDGL16)

gives an output of the form:

bkw                  :: rop: ≈2^178.8, m: ≈2^166.8, mem: ≈2^167.8, b: 14, t1: 0, t2: 16, ℓ: 13, #cod: 448, #top: 0, #test: 64, tag: coded-bkw
usvp                 :: rop: ≈2^147.9, red: ≈2^147.9, δ: 1.003941, β: 406, d: 998, tag: usvp
bdd                  :: rop: ≈2^142.6, red: ≈2^141.5, svp: ≈2^141.7, β: 384, η: 429, d: 984, tag: bdd
bdd_hybrid           :: rop: ≈2^142.6, red: ≈2^141.5, svp: ≈2^141.7, β: 384, η: 429, ζ: 0, |S|: 1, d: 1009, prob: 1, ↻: 1, tag: hybrid
bdd_mitm_hybrid      :: rop: ≈2^260.3, red: ≈2^259.4, svp: ≈2^259.2, β: 405, η: 2, ζ: 105, |S|: ≈2^255.2, d: 920, prob: ≈2^-109.7, ↻: ≈2^111.9, tag: hybrid
dual                 :: rop: ≈2^153.2, mem: ≈2^88.0, m: 512, β: 424, d: 1024, ↻: 1, tag: dual
dual_hybrid          :: rop: ≈2^148.5, mem: ≈2^145.2, m: 512, β: 407, d: 1002, ↻: 1, ζ: 22, tag: dual_hybrid


you can interpret rop as the running time of each attack, so your security level is the smallest value of rop -- in this case 2^142.6 from bdd. So this parameter set would have approx 142 bits of security under the assumptions used.
