### ISSUE TITLE
Rotation Issue of throwing an error for the second iteration whose k is not the power of 2

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#329]
Hi,
I've been following this https://github.com/tuneinsight/lattigo/discussions/327
and I found the **first** iteration could succeed, but the **second** iteration throws an error when running the rotation statement.
![image](https://user-images.githubusercontent.com/754293/209517923-8cbdefae-edf6-4a3d-a934-f52712aad2dc.png)

error:
![image](https://user-images.githubusercontent.com/754293/209517953-dc3846a7-c842-4392-be7c-dc918a173d86.png)

I'm not sure what the problem is, would you have a look? The way I use is wrong? the problem of the code itself? or some bugs?

BR

**Comment by macknight** [comment]
I found that the problem may be the rotation param "k".
for a ciphertext which consists of 64 values, I want to move the first slot right to the second slot, but this rotation function uses left move, so I should move the first slot left 63 slots, but the error shows, why?
And how to avoid this error?
BR

**Comment by macknight** [comment]
According to test,
evaluator.Rotate(encInputCopy, 0, encInputCopy) // succeed
evaluator.Rotate(encInputCopy, 1, encInputCopy) // succeed
evaluator.Rotate(encInputCopy, 2, encInputCopy) // succeed
evaluator.Rotate(encInputCopy, 3, encInputCopy) // error
evaluator.Rotate(encInputCopy, 4, encInputCopy) // succeed

**Comment by macknight** [comment]
Must all rotate relative methods in ckks.evaluator have the rotation offsets which must be the power of 2?
Then how to rotate by 3 for example? 

Does it mean I need to manually rotate 2 and then rotate 1? Cause 3 = 2+1

BR

**Comment by Pro7ech** [comment]
Hi @macknight, 

Have you made sure that you have computed the required rotations keys for your circuit?

**Comment by macknight** [comment]
> Hi @macknight,
> 
> Have you made sure that you have computed the required rotations keys for your circuit? If you are using the default ones of the example, it will indeed only work for powers of two.

Is this the default way? 

![image](https://user-images.githubusercontent.com/754293/209528479-553764e9-2b1a-4a3a-9ad1-ac244f8a4d5d.png)
BR

**Comment by Pro7ech** [comment]
@macknight You have to generate one key for each different rotation that you will use. The example in `ckks/advanced/lut` shows how to do it for the centralized scheme, and the example in `drlwe` for the threshold variant. Please make sure you research first before opening an issue.
