### ISSUE TITLE
Add way to get the rotations needed for a linear transform without having to first allocate it

### ISSUE THREAD

**Issue by Pro7ech** [tuneinsight/lattigo#342]
Hi contributors 

I found that in `ckks` GenLinearTransform(*), the index of `map[int]ringqp.Poly vec` will be set to `idx += slots ( if idx<0) or idx (if idex>=0)` . I guess this is doing `idx mod slots` . But I think this might potentially generate unexpected rotation index for me when I set logslots < logN -1, i.e. when number of slots required is exactly smaller than the maximum. For example, when `idx <0` , the galois element that GenLinearTransform generates is 5^(idx mod slots mod N/2) != 5^(idx mod N/2) , where 5^(idx mod N) is generated by  GenRotationKeysForRotations(*). Althought the two elements act in the same way, LinearTransformNew will panic when it can't find 5^(idx mod slots mod N) however 5^(idx mod N) is provided.

Not sure if my understanding is correct. But I did encountered this situation these days.

BR

_Originally posted by @lilBuffaloEric in https://github.com/tuneinsight/lattigo/discussions/334_

**Comment by Pro7ech** [comment]
I've opened an issue.

**Comment by Pro7ech** [comment]
@lilBuffaloEric could you provide us with a main that reproduces the bug?

**Comment by lilBuffaloEric** [comment]
```
package main

import (
	"errors"
	"fmt"
	"math"

	"github.com/tuneinsight/lattigo/v4/ckks"
	"github.com/tuneinsight/lattigo/v4/rlwe"
)

func Gen_sigma_diagonalVecotrs(d int) (U map[int][]float64, err error) {
	if d <= 0 {
		return nil, errors.New("dimension d <= 0 ")
	}
	U = make(map[int][]float64, 2*d-1)
	for k := -d + 1; k < d; k++ {
		U[k] = make([]float64, d*d)
		for i := 0; i < d*d; i++ {
			if k >= 0 {
				if (i-d*k) >= 0 && (i-d*k) < (d-k) {
					U[k][i] = 1
				} else {
					U[k][i] = 0
				}
			} else {
				if (i-(d+k)*d) >= -k && (i-(d+k)*d) < d {
					U[k][i] = 1
				} else {
					U[k][i] = 0
				}
			}
		}
	}
	return
}

func Sigma_linearTransform(params ckks.Parameters, rlk *rlwe.RelinearizationKey, galk *rlwe.RotationKeySet, ctIn *rlwe.Ciphertext, d int) (ctOut *rlwe.Ciphertext, err error) {
	if d <= 0 || float64(d*d) != math.Pow(2, float64(params.LogSlots())) {
		return nil, errors.New("d<0 or d^2 != 2^logSlots")
	}
	var U_sigma map[int][]float64
	U_sigma, err = Gen_sigma_diagonalVecotrs(d)
	if err != nil {
		return nil, err
	}
	Scale := ctIn.Scale
	encoder := ckks.NewEncoder(params)
	evaluator := ckks.NewEvaluator(params, rlwe.EvaluationKey{Rlk: rlk, Rtks: galk})
	sigmaLT := ckks.GenLinearTransform(encoder, U_sigma, ctIn.Level(), Scale, params.LogSlots())
	ctOut_list := evaluator.LinearTransformNew(ctIn, sigmaLT)
	ctOut = ctOut_list[0]
	err = evaluator.Rescale(ctOut, ctIn.Scale, ctOut)
	if err != nil {
		return nil, err
	}
	fmt.Printf("%d levels consumed for LinearTransform\n", ctIn.Level()-ctOut.Level())
	return
}

func main() {
	var err error
	d := 4
	MatrixA := make([]float64, d*d)
	for i := 0; i < d; i++ {
		for j := 0; j < d; j++ {
			MatrixA[i*d+j] = float64(i*d + j)
		}
	}
	// initialize encryption scheme.
	LogN := 15
	Q := []uint64{
		1152921504598720513,
		1099490000897, 1099498258433, 1099499175937, 1099499569153, 1099500617729}

	P := []uint64{1152921504606584833}
	var params ckks.Parameters
	if params, err = ckks.NewParametersFromLiteral(ckks.ParametersLiteral{
		LogN:         LogN,
		Q:            Q,
		P:            P,
		LogSlots:     int(math.Log2(float64(d * d))), // we only need 16 slots to represent a 4x4 matrix in a ciphertext.
		DefaultScale: 1 << 40,
	}); err != nil {
		panic(err)
	}
	// generate Keys:
	kgen := ckks.NewKeyGenerator(params)
	sk, pk := kgen.GenKeyPair()
	// Relinearization key
	rlk := kgen.GenRelinearizationKey(sk, 1)
	// Galois keys
	// rotation steps {-d+1 ~ d-1}
	steps := make([]int, d+d-1+d-1)
	j := 0
	for i := 0; i < d; i++ {
		steps[j] = i
		j++
		if i != 0 {
			steps[j] = -i // FIXME: -i is original but will cause panic, so we will have to set -i mod d^2 here.
			j++
		}
	}
	galk := kgen.GenRotationKeysForRotations(steps[:], false, sk)

	// Encryptor
	encryptor := ckks.NewEncryptor(params, pk)

	// encoder
	encoder := ckks.NewEncoder(params)
	// encryption
	ptA := encoder.EncodeNew(MatrixA, params.MaxLevel(), params.DefaultScale(), params.LogSlots())
	ctA := encryptor.EncryptNew(ptA)
	// Check Sigma permutation
	var ctSigmaA *rlwe.Ciphertext
	ctSigmaA, err = Sigma_linearTransform(params, rlk, galk, ctA, d)
	if err != nil {
		panic(err)
	}
	fmt.Print(ctSigmaA) // not necessary...
}
```

**Comment by lilBuffaloEric** [comment]
Sorry I cant make this simpler, but the main idea is that Gen_sigma_diagonalVectors() generate diagVectors with indexs from -d+1 to d-1, which are exactly same as the steps of rotation generated in main(). Sigma_linearTransform() is the function that conducts the transformation. 

I didnt pose the decryption and decoding procedures, since I think they are irrelevant to this issue.

**Comment by Pro7ech** [comment]
@lilBuffaloEric I have tried your code, it seems that you are manually generating the rotations. However, if you modify it to use the rotations as `rotations := sigmaLT.Rotations()` it works fine. However, there is currently no good way to get the rotations that you need without first allocating the linear transform, which isn't good. So I'll keep this issue open and rename it appropriately.

**Comment by lilBuffaloEric** [comment]
Thanks for your reply~

I'm not sure why function `ckks GenLinearTransform()` will set the index of `map[int]ringqp.Poly vec` to `idx += slots ( if idx<0)` or `idx (if idx>=0)` instead of just `idx` no matter what sign it has. This might be the place producing the problem.

**Comment by Pro7ech** [comment]
The user is allowed to give the index of the diagonals as negative values (i.e. in [slots/2, slots/2-1]), but then they are converted back to [0, slots-1] for the evaluation.

Your problem is solved if you use the API provided by the library to generate the rotations for a linear transform, so I don't see what problem you are referring too in your last sentence.

**Comment by Pro7ech** [comment]
#379
