### ISSUE TITLE
`bgv.Encoder.Encode` should fail when the values are not []uint64 or []int64

### ISSUE THREAD

**Issue by henrycg** [tuneinsight/lattigo#387]
As is, `bgv.Encoder.Encode` silently fails, which makes it more difficult to debug encoding (e.g., if you passed an array instead of slice by accident).

I think adding a `default` case to the `switch` statement here would be enough: https://github.com/tuneinsight/lattigo/blob/803a26b14d9292ffa7b2be443a49b0c27e6f90a5/bgv/encoder.go#L131

**Comment by Pro7ech** [comment]
Hi Henry, thank you for pointing it out. Improving this behavior is among the many fixes that are part of the upcoming 4.2 release.

If you have any feedback, suggestion or feature requirement, don't hesitate as the 4.2 release hasn't been finalized yet and we are still actively working on it.

**Comment by Pro7ech** [comment]
#379
