### ISSUE TITLE
Which papers the lattigo BGV/BFV implement is based on?

### ISSUE THREAD

**Issue by fangzihuan** [tuneinsight/lattigo#404]
Could you tell me which papers the lattigo BGV and BFV implement is based on?

**Comment by Pro7ech** [comment]
Implementations of BFV and BGV in Lattigo are not based a specific papers. Rather it tries to reuse as much as possible the same backed for all schemes (`ring` and `rlwe`). 

Additionally, Lattigo implements a special variant of the BGV scheme which provides the functionalities of the BGV and BFV schemes unified under a single scheme. 

The BFV scheme in Lattigo is in fact nothing more than a wrapper of the BGV scheme.

**Comment by Pro7ech** [comment]
Closed due to 3w of inactivity
