### ISSUE TITLE
Bug/Regression [bfv]: A division-by-zero panic occurs when the plaintext modulus is set to 0.

### ISSUE THREAD

**Issue by Maokami** [tuneinsight/lattigo#411]
### What version of Lattigo are you using?
4.1.0
### Does this issue persist with the latest release?
Yes
### What were you trying to do?
Manually set the plaintext modulus(t) to zero.
### What were you expecting to happen?
panic: invalid modulus: plaintext modulus cannot be zero (or, invalid modulus: 0 is not prime)
### What actually happened?
panic : division by zero
### Reproducibility

```go
package main

import (
	"github.com/tuneinsight/lattigo/v4/bfv"
)

func main() {

	paramDef := bfv.PN13QP218
	paramDef.T = 0

	_, err := bfv.NewParametersFromLiteral(paramDef)
	if err != nil {
		panic(err)
	}
}
```

**Comment by Pro7ech** [comment]
Hi @Maokami, this is fixed in the upcoming v5: https://github.com/tuneinsight/lattigo/blob/0b657a61d78d4f02fb4ca7e2509847b651ded579/schemes/bgv/params.go#L81

**Comment by Maokami** [comment]
A-ha! Thanks a lot!
