### ISSUE TITLE
About keyswitch optimization.

### ISSUE THREAD

**Issue by CHOSEN24** [tuneinsight/lattigo#439]
Hello, 
does the current version support the latest keyswitch optimization?  Such as "Accelerating HE Operations Using Key Decomposition" [KLSS23].

**Comment by Pro7ech** [comment]
Hi @CHOSEN24, Lattigo does not implement this optimisation. Although in can in theory increase the speed of the key-switching operarions by a fair amount, it also induces a prohibitive increase in the size of the keys, making this optimisation difficult to justify in practice.

It might be useful for applications that require many key-switching but use only a limited number of keys, but these are rare and it would require substantial change in the backend of the library to be implemented.

**Comment by CHOSEN24** [comment]
Thanks for your valuable response.
