### ISSUE TITLE
Encryption elements and parallelization problem

### ISSUE THREAD

**Issue by hkanpak21** [tuneinsight/lattigo#441]
Using lattigo v4.1, the issue persists.
I am trying to parallelize a simple neural network that uses lattigo elements. Whenever I try parallelization, the code works fine. However, switching to the encrypted version results in the error code mentioned in the attached file. I was expecting that the code should have worked fine since I am only parallelizing among the input data, where there are no dependencies or possible conflicts.

[Issue1322024.txt](https://github.com/tuneinsight/lattigo/files/14258560/Issue1322024.txt)

**Comment by Pro7ech** [comment]
This is an expected behavior, see #406
