### ISSUE TITLE
Question:Can I use rlwe.MemEvaluationKeySet to complete the bootstrapping?

### ISSUE THREAD

**Issue by yellow123Nike** [tuneinsight/lattigo#448]
I found that bootstrapping can only be initialized using sk，but i want use rlwe.MemEvaluationKeySet to complete the bootstrapping

**Comment by yellow123Nike** [comment]
Or, how can the bootstrapping of v2.2.0 generated by the following code be used in v5.0.2?
`	btpKey := ckks.BootstrappingKey{Rlk: rlk, Rtks: rotkeys}
	if btp, err = ckks.NewBootstrapper(params, btpParams, btpKey); err != nil {
		panic(err)
	}`

**Comment by yellow123Nike** [comment]
"Well, my program cannot know the secret key (sk), it only knows the RelinearizationKey. When calculating with polynomials, it reports an error: panic: 0 levels < 5 log(d) -> cannot evaluate poly. Is there a simple way to make the polynomial evaluation's mul change to MulRelin?"

**Comment by Pro7ech** [comment]
The issue you are running into is not related to the relinearization key but to the homomorphic capacity of the ciphertext. The error says that you would need 5 levels to evaluate the polynomial, but your ciphertext is already at level 0 (it has exhausted all its homomorphic capacity)

**Comment by SetarehGhorshi** [comment]
Hey @yellow123Nike. I am trying to initialize the bootstrapper without the sk and was wondering if you were able to do so? I am using v6 of lattigo and were not able to find a way to use the bootstrapper without the knowledge of sk and only using the ckks evaluation keys (`rlwe.MemEvaluationKeySet`).

**Comment by lehugueni** [comment]
Hi @SetarehGhorshi, 

The answer from @Pro7ech is still valid. You need to look at the keys needed for the bootstrapping in `bootstrapping.EvaluationKeys` (some of them you might not need depending on your parameters). 
Then you have to make sure that these evaluation keys can be retrieved from the `rlwe.MemEvaluationKeySet` struct. 

If you need more info, please provide more details on your requirements and open a new discussion.
