### ISSUE TITLE
"How is EncodingDomain set?"

### ISSUE THREAD

**Issue by yellow123Nike** [tuneinsight/lattigo#466]
![image](https://github.com/tuneinsight/lattigo/assets/37546857/24995f70-d2d7-49fd-ab5c-fa210a1b33ab)
"How is EncodingDomain set?"

**Comment by qantik** [comment]
Hi, the comment is a residual from an earlier Lattigo version. Whether a plaintext is in the slots or
coefficients domain is determined by the `IsBatched` field in the `PlaintextMetaData` object.

 - `IsBatched = true` -> slot encoding.
 - `IsBatched = false` -> coefficient encoding.

If the field is not set specifically by the user `IsBatched = true`.
