### ISSUE TITLE
Question: Multiply imaginary i for CKKS without increase the scale of the  ciphertext

### ISSUE THREAD

**Issue by guiming-shi** [tuneinsight/lattigo#489]
I find the imult function in HEAAN library but not this library, this realize the function
ciphertext * i, e.g., ([3, 4, -2i, i] * i = [3i, 4i, 2, -1]) without increase the scale of the 
ciphertext, is this function will be realized? thanks.

**Comment by lehugueni** [comment]
It's automatically taken care of in lattigo. If `op1` in the `Mul` function (or any variant) is a [gaussian integer](https://en.wikipedia.org/wiki/Gaussian_integer), the scale is not increased.

**Comment by guiming-shi** [comment]
Thanks
