### ISSUE TITLE
Does multiparty BFV or BGV in Lattigo supports modulus switching?

### ISSUE THREAD

**Issue by lqwww-w** [tuneinsight/lattigo#494]
Hi,

I am currently exploring the multiparty homomorphic encryption features in the Lattigo library. However, I could not find any specific functions or methods that implement modulus switching in the documentation or source code.

Could you please confirm whether modulus switching is supported in Lattigo's multiparty BFV or BGV implementation? If it is, could you provide some guidance or an example on how to use this feature?

Thank you for your help!

Best regards,
Qingwen

**Comment by Pro7ech** [comment]
The multiparty aspects of Lattigo only relate to the key generation, interactive bootstrapping and decryption/recryption to the secret shared domain.

Everything else is identical to the single party setting and the single party packages for everything related to the circuit evaluation.
