### ISSUE TITLE
Question:  The reason for the existence of the secret key bootstrapper

### ISSUE THREAD

**Issue by Seungho-Kim-SKKU** [tuneinsight/lattigo#507]
I implemented the built-in Sign function in Lattigo by following your comparison_test.go example. 
I noticed that the secret key is used when creating the bootstrapper, which is then passed as an argument to NewComparisonEvaluator. And I observed that the bootstrap function, which uses this secret key bootstrapper, performs decryption and re-encryption during the bootstrapping process.

In a server-client model, assuming the server needs to use the Sign function, the secret key would be exposed to the server.

My question is why is the secret key bootstrapper necessary? I am unsure in which scenario it would be appropriate to use this.

**Comment by Pro7ech** [comment]
The secret key bootstrapper is used for testing purposes. In practice you would pass an actual bootstrapper.

**Comment by Seungho-Kim-SKKU** [comment]
Okay. Thank you :)
