### ISSUE TITLE
Bug/Regression [<package>]:Bootstrap Evaluator ShallowCopy wrong parameter parser.

### ISSUE THREAD

**Issue by nc26676027** [tuneinsight/lattigo#514]
### What version of Lattigo are you using?
The latest version of lattigo
### Does this issue persist with the latest release?
Yes
### What were you trying to do?
Enable multi-threading bootstrapping
### Reproducibility
Yes

Should be the following:
	return &Evaluator{
		Parameters:     eval.Parameters,
		EvaluationKeys: eval.EvaluationKeys,
		Mod1Parameters: eval.Mod1Parameters,
		S2CDFTMatrix:   eval.S2CDFTMatrix,
		C2SDFTMatrix:   eval.C2SDFTMatrix,
		Evaluator:      heEvaluator,
		xPow2N1:        eval.xPow2N1,
		xPow2N2:        eval.xPow2N2,
		xPow2InvN2:     eval.xPow2InvN2,
		DomainSwitcher: DomainSwitcher,
		DFTEvaluator:   dft.NewEvaluator(paramsN2, heEvaluator), // Chao add paramsN1 -> paramsN2
		Mod1Evaluator:  mod1.NewEvaluator(heEvaluator, polynomial.NewEvaluator(paramsN2, heEvaluator), eval.Mod1Parameters),
		SkDebug:        eval.SkDebug,
	}

**Comment by lehugueni** [comment]
Thanks! I've added the fix as part of #506
